BB_CONF_FRAGMENT_SUMMARY = "Add Testing depenencies for Home Assistant"
BB_CONF_FRAGMENT_DESCRIPTION = "\
    This fragment adds missing dependencies for running Home Assistant tests. \
"

CORE_IMAGE_EXTRA_INSTALL:append = " \
    ptest-runner \
    python3-homeassistant-ptest \
"
