BB_CONF_FRAGMENT_SUMMARY = "Add Qemu Testing"
BB_CONF_FRAGMENT_DESCRIPTION = "\
    This fragment ensures that any QEMU image is not limited by CPU or RAM. \
    Moreover this ensures that any image is automatically run and a default set of TEST_SUITES are run.\
"

IMAGE_CLASSES += "testimage"
TESTIMAGE_AUTO = "1"
TEST_RUNQEMUPARAMS:append = " slirp snapshot kvm"
TEST_SUITES = "\
    date \
    df \
    ping \
    ptest \
    scp \
    ssh \
"
CORE_IMAGE_EXTRA_INSTALL:append = " \
    ptest-runner \
    python3-homeassistant-ptest \
"

# Enlarge the default memory and CPU limits for QEMU when running tests.
QB_MEM ?= "-m 8G"
QB_SMP = "-smp 12"
