BB_CONF_FRAGMENT_SUMMARY = "Add commercial licenses support"
BB_CONF_FRAGMENT_DESCRIPTION = "\
    This fragment adds commercial licenses support \
"

LICENSE_FLAGS_ACCEPTED = "\
    commercial_ffmpeg \
    commercial_libde265 \
    commercial_libheif \
    commercial_openh264 \
    commercial_python3-pillow-heif \
    commercial_x265 \
"