name: Gitea HomeAssistant Build Actions
run-name: ${{ gitea.actor }} is building the HomeAssistant project
on:
  push:

jobs:
  Build:
    runs-on: yocto-builder
    env:
      GITHUB_STATUS_CONTEXT: gitea/homeassistant-build
      GITHUB_STATUS_REPOSITORY: meta-homeassistant/meta-homeassistant
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    container:
      volumes:
          - /cache/:/cache/
          - /dev/kvm:/dev/kvm/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set GitHub status to pending
        uses: ./.gitea/actions/github-status
        with:
          status-token: ${{ secrets.STATUS_TOKEN }}
          github-status-context: ${{ env.GITHUB_STATUS_CONTEXT }}
          github-status-repository: ${{ env.GITHUB_STATUS_REPOSITORY }}
          sha: ${{ gitea.sha }}
          state: pending
      - name: Build HA
        shell: bash
        run: |
          echo "Cloning bitbake"
          git clone https://git.openembedded.org/bitbake sources/bitbake
          echo "Initializing Yocto build directory"
          sources/bitbake/bin/bitbake-setup \
            --setting default top-dir-prefix /cache/builddir/ \
            init \
            --non-interactive \
            configurations/homeassistant.conf.json homeassistant-x86 \
            --source-overrides ${{ gitea.workspace }}/configurations/gitea-ci.json
          echo "Sourcing environment"
          source /cache/builddir/bitbake-builds/homeassistant-x86/build/init-build-env
          echo "Starting build"
          bitbake core-image-homeassistant-full |& tee "${{ gitea.workspace }}/build.log"
      - name: Set GitHub status to success
        if: success()
        uses: ./.gitea/actions/github-status
        with:
          status-token: ${{ secrets.STATUS_TOKEN }}
          github-status-context: ${{ env.GITHUB_STATUS_CONTEXT }}
          github-status-repository: ${{ env.GITHUB_STATUS_REPOSITORY }}
          sha: ${{ gitea.sha }}
          state: success
      - name: Set GitHub status to failure
        if: failure()
        uses: ./.gitea/actions/github-status
        with:
          status-token: ${{ secrets.STATUS_TOKEN }}
          github-status-context: ${{ env.GITHUB_STATUS_CONTEXT }}
          github-status-repository: ${{ env.GITHUB_STATUS_REPOSITORY }}
          sha: ${{ gitea.sha }}
          state: failure

  Basic-Test:
    runs-on: yocto-builder
    needs: Build
    env:
      GITHUB_STATUS_CONTEXT: gitea/homeassistant-basic-test
      GITHUB_STATUS_REPOSITORY: meta-homeassistant/meta-homeassistant
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    container:
      volumes:
          - /cache/:/cache/
          - /dev/kvm:/dev/kvm/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set GitHub status to pending
        uses: ./.gitea/actions/github-status
        with:
          status-token: ${{ secrets.STATUS_TOKEN }}
          github-status-context: ${{ env.GITHUB_STATUS_CONTEXT }}
          github-status-repository: ${{ env.GITHUB_STATUS_REPOSITORY }}
          sha: ${{ gitea.sha }}
          state: pending
      - name: Basic test HA
        shell: bash
        run: |
          echo "Cloning bitbake"
          git clone https://git.openembedded.org/bitbake sources/bitbake
          echo "Building and testing"
          source /cache/builddir/bitbake-builds/homeassistant-x86/build/init-build-env
          bash ${{ gitea.workspace }}/tests/test-basic-homeassistant.sh
      - name: Set GitHub status to success
        if: success()
        uses: ./.gitea/actions/github-status
        with:
          status-token: ${{ secrets.STATUS_TOKEN }}
          github-status-context: ${{ env.GITHUB_STATUS_CONTEXT }}
          github-status-repository: ${{ env.GITHUB_STATUS_REPOSITORY }}
          sha: ${{ gitea.sha }}
          state: success
      - name: Set GitHub status to failure
        if: failure()
        uses: ./.gitea/actions/github-status
        with:
          status-token: ${{ secrets.STATUS_TOKEN }}
          github-status-context: ${{ env.GITHUB_STATUS_CONTEXT }}
          github-status-repository: ${{ env.GITHUB_STATUS_REPOSITORY }}
          sha: ${{ gitea.sha }}
          state: failure
