require conf/distro/poky.conf

DISTRO = "homeassistant"
DISTRO_NAME = "HomeAssistant Linux Distro"
DISTRO_VERSION = "0.1"

DISTRO_FEATURES += "\
    virtualization \
"

INIT_MANAGER = "systemd"

# python3-pybind11-native fails to build without a newer version of ninja
PREFERRED_VERSION_python3-pybind11 = "2.13.6"
PREFERRED_VERSION_python3-pybind11-native = "2.13.6"

BBMASK += "recipes-python/fsspec/python3-fsspec_2025.5.1.bbappend"

FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"
HOSTTOOLS += "gfortran"
