INTEGRATIONS = "\
    ${PN}-3-day-blinds \
    ${PN}-acaia \
    ${PN}-accuweather \
    ${PN}-acer-projector \
    ${PN}-acmeda \
    ${PN}-acomax \
    ${PN}-actiontec \
    ${PN}-adax \
    ${PN}-adguard \
    ${PN}-advantage-air \
    ${PN}-aemet \
    ${PN}-aep-ohio \
    ${PN}-aep-texas \
    ${PN}-aftership \
    ${PN}-agent-dvr \
    ${PN}-ai-task \
    ${PN}-air-quality \
    ${PN}-airgradient \
    ${PN}-airly \
    ${PN}-airnow \
    ${PN}-airos \
    ${PN}-airq \
    ${PN}-airthings \
    ${PN}-airthings-ble \
    ${PN}-airtouch4 \
    ${PN}-airtouch5 \
    ${PN}-airvisual \
    ${PN}-airvisual-pro \
    ${PN}-airzone \
    ${PN}-airzone-cloud \
    ${PN}-aladdin-connect \
    ${PN}-alarm-control-panel \
    ${PN}-alarmdecoder \
    ${PN}-alert \
    ${PN}-alexa \
    ${PN}-alpha-vantage \
    ${PN}-altruist \
    ${PN}-amazon-polly \
    ${PN}-amberelectric \
    ${PN}-ambient-network \
    ${PN}-ambient-station \
    ${PN}-amcrest \
    ${PN}-amp-motorization \
    ${PN}-ampio \
    ${PN}-analytics \
    ${PN}-analytics-insights \
    ${PN}-android-ip-webcam \
    ${PN}-androidtv \
    ${PN}-androidtv-remote \
    ${PN}-anel-pwrctrl \
    ${PN}-anova \
    ${PN}-anthemav \
    ${PN}-anthropic \
    ${PN}-anwb-energie \
    ${PN}-aosmith \
    ${PN}-apache-kafka \
    ${PN}-apcupsd \
    ${PN}-api \
    ${PN}-apollo-automation \
    ${PN}-appalachianpower \
    ${PN}-apple-tv \
    ${PN}-application-credentials \
    ${PN}-aprilaire \
    ${PN}-aprs \
    ${PN}-apsystems \
    ${PN}-aqualogic \
    ${PN}-aquostv \
    ${PN}-aranet \
    ${PN}-arcam-fmj \
    ${PN}-arest \
    ${PN}-arris-tg2492lg \
    ${PN}-artsound \
    ${PN}-aruba \
    ${PN}-arve \
    ${PN}-arwn \
    ${PN}-aseko-pool-live \
    ${PN}-assist-pipeline \
    ${PN}-assist-satellite \
    ${PN}-asuswrt \
    ${PN}-atag \
    ${PN}-aten-pe \
    ${PN}-atlanticcityelectric \
    ${PN}-atome \
    ${PN}-august \
    ${PN}-august-ble \
    ${PN}-aurora \
    ${PN}-aurora-abb-powerone \
    ${PN}-aussie-broadband \
    ${PN}-autarco \
    ${PN}-auth \
    ${PN}-automation \
    ${PN}-avea \
    ${PN}-avion \
    ${PN}-awair \
    ${PN}-aws \
    ${PN}-aws-s3 \
    ${PN}-axis \
    ${PN}-azure-data-explorer \
    ${PN}-azure-devops \
    ${PN}-azure-event-hub \
    ${PN}-azure-service-bus \
    ${PN}-azure-storage \
    ${PN}-backup \
    ${PN}-baf \
    ${PN}-baidu \
    ${PN}-balay \
    ${PN}-balboa \
    ${PN}-bang-olufsen \
    ${PN}-bauknecht \
    ${PN}-bayesian \
    ${PN}-bbox \
    ${PN}-beewi-smartclim \
    ${PN}-bge \
    ${PN}-binary-sensor \
    ${PN}-bitcoin \
    ${PN}-bizkaibus \
    ${PN}-blackbird \
    ${PN}-blebox \
    ${PN}-blink \
    ${PN}-blinksticklight \
    ${PN}-bliss-automation \
    ${PN}-bloc-blinds \
    ${PN}-blockchain \
    ${PN}-blue-current \
    ${PN}-bluemaestro \
    ${PN}-blueprint \
    ${PN}-bluesound \
    ${PN}-bluetooth \
    ${PN}-bluetooth-adapters \
    ${PN}-bluetooth-le-tracker \
    ${PN}-bmw-connected-drive \
    ${PN}-bond \
    ${PN}-bosch-alarm \
    ${PN}-bosch-shc \
    ${PN}-brands \
    ${PN}-brandt \
    ${PN}-braviatv \
    ${PN}-brel-home \
    ${PN}-bring \
    ${PN}-broadlink \
    ${PN}-brother \
    ${PN}-brottsplatskartan \
    ${PN}-browser \
    ${PN}-brunt \
    ${PN}-bryant-evolution \
    ${PN}-bsblan \
    ${PN}-bswitch \
    ${PN}-bt-home-hub-5 \
    ${PN}-bt-smarthub \
    ${PN}-bthome \
    ${PN}-bticino \
    ${PN}-bubendorff \
    ${PN}-buienradar \
    ${PN}-burbank-water-and-power \
    ${PN}-button \
    ${PN}-caldav \
    ${PN}-calendar \
    ${PN}-cambridge-audio \
    ${PN}-camera \
    ${PN}-canary \
    ${PN}-cast \
    ${PN}-ccm15 \
    ${PN}-cert-expiry \
    ${PN}-chacon-dio \
    ${PN}-channels \
    ${PN}-cisco-ios \
    ${PN}-cisco-mobility-express \
    ${PN}-cisco-webex-teams \
    ${PN}-clementine \
    ${PN}-clickatell \
    ${PN}-clicksend \
    ${PN}-clicksend-tts \
    ${PN}-climate \
    ${PN}-cloud \
    ${PN}-cloudflare \
    ${PN}-cloudflare-r2 \
    ${PN}-cmus \
    ${PN}-co2signal \
    ${PN}-coautilities \
    ${PN}-coinbase \
    ${PN}-color-extractor \
    ${PN}-comed \
    ${PN}-comed-hourly-pricing \
    ${PN}-comelit \
    ${PN}-comfoconnect \
    ${PN}-command-line \
    ${PN}-compensation \
    ${PN}-concord232 \
    ${PN}-coned \
    ${PN}-config \
    ${PN}-configurator \
    ${PN}-constructa \
    ${PN}-control4 \
    ${PN}-conversation \
    ${PN}-cookidoo \
    ${PN}-coolmaster \
    ${PN}-cosori \
    ${PN}-counter \
    ${PN}-cover \
    ${PN}-cozytouch \
    ${PN}-cppm-tracker \
    ${PN}-cpuspeed \
    ${PN}-cribl \
    ${PN}-crownstone \
    ${PN}-currencylayer \
    ${PN}-dacia \
    ${PN}-daikin \
    ${PN}-danfoss-air \
    ${PN}-datadog \
    ${PN}-date \
    ${PN}-datetime \
    ${PN}-ddwrt \
    ${PN}-deako \
    ${PN}-debugpy \
    ${PN}-deconz \
    ${PN}-decora-wifi \
    ${PN}-decorquip \
    ${PN}-default-config \
    ${PN}-delijn \
    ${PN}-delmarva \
    ${PN}-deluge \
    ${PN}-demo \
    ${PN}-denon \
    ${PN}-denonavr \
    ${PN}-derivative \
    ${PN}-devialet \
    ${PN}-device-automation \
    ${PN}-device-sun-light-trigger \
    ${PN}-device-tracker \
    ${PN}-devolo-home-control \
    ${PN}-devolo-home-network \
    ${PN}-dexcom \
    ${PN}-dhcp \
    ${PN}-diagnostics \
    ${PN}-dialogflow \
    ${PN}-diaz \
    ${PN}-digital-loggers \
    ${PN}-digital-ocean \
    ${PN}-directv \
    ${PN}-discogs \
    ${PN}-discord \
    ${PN}-discovergy \
    ${PN}-dlink \
    ${PN}-dlna-dmr \
    ${PN}-dlna-dms \
    ${PN}-dnsip \
    ${PN}-doods \
    ${PN}-doorbird \
    ${PN}-dooya \
    ${PN}-dormakaba-dkey \
    ${PN}-dovado \
    ${PN}-downloader \
    ${PN}-dremel-3d-printer \
    ${PN}-drop-connect \
    ${PN}-dsmr \
    ${PN}-dsmr-reader \
    ${PN}-dublin-bus-transport \
    ${PN}-duckdns \
    ${PN}-duke-energy \
    ${PN}-dunehd \
    ${PN}-duotecno \
    ${PN}-duquesne-light \
    ${PN}-dwd-weather-warnings \
    ${PN}-dynalite \
    ${PN}-eafm \
    ${PN}-eastron \
    ${PN}-easyenergy \
    ${PN}-ebox \
    ${PN}-ebusd \
    ${PN}-ecoal-boiler \
    ${PN}-ecobee \
    ${PN}-ecoforest \
    ${PN}-econet \
    ${PN}-ecovacs \
    ${PN}-ecowitt \
    ${PN}-edimax \
    ${PN}-edl21 \
    ${PN}-efergy \
    ${PN}-egardia \
    ${PN}-eheimdigital \
    ${PN}-eight-sleep \
    ${PN}-electrasmart \
    ${PN}-electric-kiwi \
    ${PN}-elevenlabs \
    ${PN}-elgato \
    ${PN}-eliqonline \
    ${PN}-elkm1 \
    ${PN}-elmax \
    ${PN}-elv \
    ${PN}-elvia \
    ${PN}-emby \
    ${PN}-emoncms \
    ${PN}-emoncms-history \
    ${PN}-emonitor \
    ${PN}-emulated-hue \
    ${PN}-emulated-kasa \
    ${PN}-emulated-roku \
    ${PN}-energenie-power-sockets \
    ${PN}-energie-vanons \
    ${PN}-energy \
    ${PN}-energyzero \
    ${PN}-enigma2 \
    ${PN}-enocean \
    ${PN}-enphase-envoy \
    ${PN}-entur-public-transport \
    ${PN}-environment-canada \
    ${PN}-envisalink \
    ${PN}-ephember \
    ${PN}-epic-games-store \
    ${PN}-epion \
    ${PN}-epson \
    ${PN}-eq3btsmart \
    ${PN}-escea \
    ${PN}-esera-onewire \
    ${PN}-esphome \
    ${PN}-etherscan \
    ${PN}-eufy \
    ${PN}-eufylife-ble \
    ${PN}-event \
    ${PN}-evergy \
    ${PN}-everlights \
    ${PN}-evil-genius-labs \
    ${PN}-evohome \
    ${PN}-ezviz \
    ${PN}-faa-delays \
    ${PN}-facebook \
    ${PN}-fail2ban \
    ${PN}-familyhub \
    ${PN}-fan \
    ${PN}-fastdotcom \
    ${PN}-feedreader \
    ${PN}-ffmpeg \
    ${PN}-ffmpeg-motion \
    ${PN}-ffmpeg-noise \
    ${PN}-fibaro \
    ${PN}-fido \
    ${PN}-file \
    ${PN}-file-upload \
    ${PN}-filesize \
    ${PN}-filter \
    ${PN}-fints \
    ${PN}-fire-tv \
    ${PN}-fireservicerota \
    ${PN}-firmata \
    ${PN}-fitbit \
    ${PN}-fivem \
    ${PN}-fixer \
    ${PN}-fjaraskupan \
    ${PN}-fleetgo \
    ${PN}-flexit \
    ${PN}-flexit-bacnet \
    ${PN}-flexom \
    ${PN}-flic \
    ${PN}-flipr \
    ${PN}-flo \
    ${PN}-flock \
    ${PN}-flume \
    ${PN}-flux \
    ${PN}-flux-led \
    ${PN}-folder \
    ${PN}-folder-watcher \
    ${PN}-foobot \
    ${PN}-forecast-solar \
    ${PN}-forked-daapd \
    ${PN}-fortios \
    ${PN}-foscam \
    ${PN}-foursquare \
    ${PN}-frankever \
    ${PN}-free-mobile \
    ${PN}-freebox \
    ${PN}-freedns \
    ${PN}-freedompro \
    ${PN}-fritz \
    ${PN}-fritzbox \
    ${PN}-fritzbox-callmonitor \
    ${PN}-fronius \
    ${PN}-frontend \
    ${PN}-frontier-silicon \
    ${PN}-fujitsu-anywair \
    ${PN}-fujitsu-fglair \
    ${PN}-fully-kiosk \
    ${PN}-futurenow \
    ${PN}-fyta \
    ${PN}-gaggenau \
    ${PN}-garadget \
    ${PN}-garages-amsterdam \
    ${PN}-gardena-bluetooth \
    ${PN}-gaviota \
    ${PN}-gc100 \
    ${PN}-gdacs \
    ${PN}-generic \
    ${PN}-generic-hygrostat \
    ${PN}-generic-thermostat \
    ${PN}-geniushub \
    ${PN}-geo-json-events \
    ${PN}-geo-location \
    ${PN}-geo-rss-events \
    ${PN}-geocaching \
    ${PN}-geofency \
    ${PN}-geonetnz-quakes \
    ${PN}-geonetnz-volcano \
    ${PN}-gios \
    ${PN}-github \
    ${PN}-gitlab-ci \
    ${PN}-gitter \
    ${PN}-glances \
    ${PN}-go2rtc \
    ${PN}-goalzero \
    ${PN}-gogogate2 \
    ${PN}-goodwe \
    ${PN}-google \
    ${PN}-google-assistant \
    ${PN}-google-assistant-sdk \
    ${PN}-google-cloud \
    ${PN}-google-drive \
    ${PN}-google-generative-ai-conversation \
    ${PN}-google-mail \
    ${PN}-google-maps \
    ${PN}-google-photos \
    ${PN}-google-pubsub \
    ${PN}-google-sheets \
    ${PN}-google-tasks \
    ${PN}-google-translate \
    ${PN}-google-travel-time \
    ${PN}-google-wifi \
    ${PN}-govee-ble \
    ${PN}-govee-light-local \
    ${PN}-gpsd \
    ${PN}-gpslogger \
    ${PN}-graphite \
    ${PN}-gree \
    ${PN}-greeneye-monitor \
    ${PN}-greenwave \
    ${PN}-group \
    ${PN}-growatt-server \
    ${PN}-gtfs \
    ${PN}-guardian \
    ${PN}-hardkernel \
    ${PN}-hardware \
    ${PN}-harvey \
    ${PN}-hassio \
    ${PN}-havana-shade \
    ${PN}-haveibeenpwned \
    ${PN}-hddtemp \
    ${PN}-heicko \
    ${PN}-heiwa \
    ${PN}-hexaom \
    ${PN}-hi-kumo \
    ${PN}-history \
    ${PN}-history-stats \
    ${PN}-hitron-coda \
    ${PN}-home-plus-control \
    ${PN}-homeassistant \
    ${PN}-homeassistant-alerts \
    ${PN}-homeassistant-connect-zbt2 \
    ${PN}-homeassistant-green \
    ${PN}-homeassistant-sky-connect \
    ${PN}-homeassistant-yellow \
    ${PN}-homekit \
    ${PN}-http \
    ${PN}-hue \
    ${PN}-humidifier \
    ${PN}-hurrican-shutters-wholesale \
    ${PN}-husqvarna-automower-ble \
    ${PN}-ibeacon \
    ${PN}-image \
    ${PN}-image-processing \
    ${PN}-image-upload \
    ${PN}-indianamichiganpower \
    ${PN}-input-boolean \
    ${PN}-input-button \
    ${PN}-input-datetime \
    ${PN}-input-number \
    ${PN}-input-select \
    ${PN}-input-text \
    ${PN}-inspired-shades \
    ${PN}-integration \
    ${PN}-intent \
    ${PN}-intent-script \
    ${PN}-ios \
    ${PN}-ipp \
    ${PN}-isal \
    ${PN}-ismartwindow \
    ${PN}-itunes \
    ${PN}-juicenet \
    ${PN}-kaiser-nienhaus \
    ${PN}-kankun \
    ${PN}-kentuckypower \
    ${PN}-keyboard-remote \
    ${PN}-kitchen-sink \
    ${PN}-konnected-esphome \
    ${PN}-krispol \
    ${PN}-kwb \
    ${PN}-labs \
    ${PN}-lannouncer \
    ${PN}-lawn-mower \
    ${PN}-legrand \
    ${PN}-letpot \
    ${PN}-levoit \
    ${PN}-life360 \
    ${PN}-lifx-cloud \
    ${PN}-light \
    ${PN}-linak \
    ${PN}-linkedgo \
    ${PN}-linksys-smart \
    ${PN}-linx \
    ${PN}-llamalab-automate \
    ${PN}-local-calendar \
    ${PN}-local-file \
    ${PN}-local-ip \
    ${PN}-local-todo \
    ${PN}-locative \
    ${PN}-lock \
    ${PN}-logbook \
    ${PN}-logentries \
    ${PN}-logger \
    ${PN}-london-air \
    ${PN}-lovelace \
    ${PN}-luftdaten \
    ${PN}-luxaflex \
    ${PN}-madeco \
    ${PN}-manual \
    ${PN}-manual-mqtt \
    ${PN}-marantz \
    ${PN}-martec \
    ${PN}-matter \
    ${PN}-maytag \
    ${PN}-mazda \
    ${PN}-mcp \
    ${PN}-mcp-server \
    ${PN}-media-player \
    ${PN}-media-source \
    ${PN}-meraki \
    ${PN}-met \
    ${PN}-microsoft-face \
    ${PN}-microsoft-face-detect \
    ${PN}-microsoft-face-identify \
    ${PN}-mijndomein-energie \
    ${PN}-min-max \
    ${PN}-mini-connected \
    ${PN}-mjpeg \
    ${PN}-mobile-app \
    ${PN}-modbus \
    ${PN}-mold-indicator \
    ${PN}-monessen \
    ${PN}-moon \
    ${PN}-mqtt \
    ${PN}-mqtt-eventstream \
    ${PN}-mqtt-json \
    ${PN}-mqtt-room \
    ${PN}-mqtt-statestream \
    ${PN}-my \
    ${PN}-myq \
    ${PN}-namecheapdns \
    ${PN}-national-grid-us \
    ${PN}-neff \
    ${PN}-neo \
    ${PN}-network \
    ${PN}-nexity \
    ${PN}-nmap-tracker \
    ${PN}-no-ip \
    ${PN}-norway-air \
    ${PN}-notify \
    ${PN}-number \
    ${PN}-nutrichef \
    ${PN}-octoprint \
    ${PN}-ogemray \
    ${PN}-ohmconnect \
    ${PN}-onboarding \
    ${PN}-oncue \
    ${PN}-openai-conversation \
    ${PN}-openalpr-cloud \
    ${PN}-openhardwaremonitor \
    ${PN}-oru-opower \
    ${PN}-otp \
    ${PN}-owntracks \
    ${PN}-panel-custom \
    ${PN}-pcs-lighting \
    ${PN}-peblar \
    ${PN}-peco \
    ${PN}-peco-opower \
    ${PN}-pepco \
    ${PN}-persistent-notification \
    ${PN}-person \
    ${PN}-pge \
    ${PN}-picotts \
    ${PN}-pinecil \
    ${PN}-ping \
    ${PN}-pioneer \
    ${PN}-piper \
    ${PN}-pitsos \
    ${PN}-plant \
    ${PN}-plum-lightpad \
    ${PN}-portlandgeneral \
    ${PN}-private-ble-device \
    ${PN}-profilo \
    ${PN}-proximity \
    ${PN}-proxy \
    ${PN}-pse \
    ${PN}-psoklahoma \
    ${PN}-pulseaudio-loopback \
    ${PN}-push \
    ${PN}-pushsafer \
    ${PN}-quadrafire \
    ${PN}-qwikswitch \
    ${PN}-radio-browser \
    ${PN}-random \
    ${PN}-raspberry-pi \
    ${PN}-raven-rock-mfg \
    ${PN}-recorder \
    ${PN}-recovery-mode \
    ${PN}-remote \
    ${PN}-remote-calendar \
    ${PN}-repairs \
    ${PN}-rest \
    ${PN}-rest-command \
    ${PN}-rexel \
    ${PN}-rhasspy \
    ${PN}-route53 \
    ${PN}-rss-feed-template \
    ${PN}-rtorrent \
    ${PN}-ruuvi-gateway \
    ${PN}-samsam \
    ${PN}-scene \
    ${PN}-schedule \
    ${PN}-scl \
    ${PN}-scrape \
    ${PN}-screenaway \
    ${PN}-script \
    ${PN}-search \
    ${PN}-select \
    ${PN}-sense \
    ${PN}-sensor \
    ${PN}-sensorblue \
    ${PN}-sentry \
    ${PN}-serial \
    ${PN}-seven-segments \
    ${PN}-sftp-storage \
    ${PN}-shell-command \
    ${PN}-shelly \
    ${PN}-shopping-list \
    ${PN}-siemens \
    ${PN}-sigfox \
    ${PN}-simplisafe \
    ${PN}-simply-automated \
    ${PN}-simu \
    ${PN}-siren \
    ${PN}-sleep-as-android \
    ${PN}-smart-blinds \
    ${PN}-smart-home \
    ${PN}-smart-rollos \
    ${PN}-smarther \
    ${PN}-smartthings \
    ${PN}-smtp \
    ${PN}-smud \
    ${PN}-snmp \
    ${PN}-somfy \
    ${PN}-sony-projector \
    ${PN}-spaceapi \
    ${PN}-speedtestdotnet \
    ${PN}-spider \
    ${PN}-spotify \
    ${PN}-sql \
    ${PN}-ssdp \
    ${PN}-startca \
    ${PN}-statistics \
    ${PN}-steam-online \
    ${PN}-stream \
    ${PN}-stt \
    ${PN}-sun \
    ${PN}-sunweg \
    ${PN}-supervisord \
    ${PN}-swepco \
    ${PN}-swisscom \
    ${PN}-switch \
    ${PN}-switch-as-x \
    ${PN}-switchbot \
    ${PN}-symfonisk \
    ${PN}-synology-chat \
    ${PN}-syslog \
    ${PN}-system-health \
    ${PN}-system-log \
    ${PN}-systemmonitor \
    ${PN}-tag \
    ${PN}-tcp \
    ${PN}-ted5000 \
    ${PN}-telegram \
    ${PN}-telnet \
    ${PN}-template \
    ${PN}-text \
    ${PN}-thermador \
    ${PN}-thermoplus \
    ${PN}-thomson \
    ${PN}-threshold \
    ${PN}-tibber \
    ${PN}-time \
    ${PN}-time-date \
    ${PN}-timer \
    ${PN}-tod \
    ${PN}-todo \
    ${PN}-tomato \
    ${PN}-torque \
    ${PN}-tplink-tapo \
    ${PN}-trace \
    ${PN}-trafikverket-camera \
    ${PN}-trafikverket-ferry \
    ${PN}-trafikverket-train \
    ${PN}-trafikverket-weatherstation \
    ${PN}-trend \
    ${PN}-tts \
    ${PN}-twilio-call \
    ${PN}-twilio-sms \
    ${PN}-ubiwizz \
    ${PN}-ublockout \
    ${PN}-uk-transport \
    ${PN}-ultraloq \
    ${PN}-universal \
    ${PN}-update \
    ${PN}-upnp \
    ${PN}-uprise-smart-shades \
    ${PN}-uptime \
    ${PN}-usage-prediction \
    ${PN}-usb \
    ${PN}-utility-meter \
    ${PN}-vacuum \
    ${PN}-vagner-pool \
    ${PN}-valve \
    ${PN}-vermont-castings \
    ${PN}-vlc \
    ${PN}-voicerss \
    ${PN}-volvooncall \
    ${PN}-w800rf32 \
    ${PN}-wake-word \
    ${PN}-wakeonlan \
    ${PN}-water-heater \
    ${PN}-weather \
    ${PN}-web-rtc \
    ${PN}-webhook \
    ${PN}-websocket-api \
    ${PN}-whisper \
    ${PN}-wirelesstag \
    ${PN}-worldclock \
    ${PN}-worldtidesinfo \
    ${PN}-worxlandroid \
    ${PN}-x10 \
    ${PN}-xiaomi \
    ${PN}-yale \
    ${PN}-yalexs-ble \
    ${PN}-yandextts \
    ${PN}-zabbix \
    ${PN}-zbox-hub \
    ${PN}-zengge \
    ${PN}-zeroconf \
    ${PN}-zestimate \
    ${PN}-zha \
    ${PN}-zodiac \
    ${PN}-zondergas \
    ${PN}-zone \
    ${PN}-zoneminder \
    ${PN}-zwave-js \
    ${PN}-zwave-me \
"

PACKAGES += "${INTEGRATIONS}"
RRECOMMENDS:${PN} += "${INTEGRATIONS}"

ALLOW_EMPTY:${PN}-3-day-blinds = "1"

ALLOW_EMPTY:${PN}-acaia = "1"
RDEPENDS:${PN}-acaia = "\
    python3-aioacaia (>=0.1.14) \
"

ALLOW_EMPTY:${PN}-accuweather = "1"
RDEPENDS:${PN}-accuweather = "\
    python3-accuweather (>=4.2.1) \
"

ALLOW_EMPTY:${PN}-acer-projector = "1"
RDEPENDS:${PN}-acer-projector = "\
    python3-pyserial (>=3.5) \
"

ALLOW_EMPTY:${PN}-acmeda = "1"
RDEPENDS:${PN}-acmeda = "\
    python3-aiopulse (>=0.4.6) \
"

ALLOW_EMPTY:${PN}-acomax = "1"

ALLOW_EMPTY:${PN}-actiontec = "1"

ALLOW_EMPTY:${PN}-adax = "1"
RDEPENDS:${PN}-adax = "\
    python3-adax (>=0.4.0) \
    python3-adax-local (>=0.1.5) \
"

ALLOW_EMPTY:${PN}-adguard = "1"
RDEPENDS:${PN}-adguard = "\
    python3-adguardhome (>=0.7.0) \
"

ALLOW_EMPTY:${PN}-advantage-air = "1"
RDEPENDS:${PN}-advantage-air = "\
    python3-advantage-air (>=0.4.4) \
"

ALLOW_EMPTY:${PN}-aemet = "1"
RDEPENDS:${PN}-aemet = "\
    python3-aemet-opendata (>=0.6.4) \
"

ALLOW_EMPTY:${PN}-aep-ohio = "1"

ALLOW_EMPTY:${PN}-aep-texas = "1"

ALLOW_EMPTY:${PN}-aftership = "1"
RDEPENDS:${PN}-aftership = "\
    python3-pyaftership (>=21.11.0) \
"

ALLOW_EMPTY:${PN}-agent-dvr = "1"
RDEPENDS:${PN}-agent-dvr = "\
    python3-agent-py (>=0.0.24) \
"

ALLOW_EMPTY:${PN}-ai-task = "1"

ALLOW_EMPTY:${PN}-air-quality = "1"

ALLOW_EMPTY:${PN}-airgradient = "1"
RDEPENDS:${PN}-airgradient = "\
    python3-airgradient (>=0.9.2) \
"

ALLOW_EMPTY:${PN}-airly = "1"
RDEPENDS:${PN}-airly = "\
    python3-airly (>=1.1.0) \
"

ALLOW_EMPTY:${PN}-airnow = "1"
RDEPENDS:${PN}-airnow = "\
    python3-pyairnow (>=1.3.1) \
"

ALLOW_EMPTY:${PN}-airos = "1"
RDEPENDS:${PN}-airos = "\
    python3-airos (>=0.4.4) \
"

ALLOW_EMPTY:${PN}-airq = "1"
RDEPENDS:${PN}-airq = "\
    python3-aioairq (>=0.4.6) \
"

ALLOW_EMPTY:${PN}-airthings = "1"
RDEPENDS:${PN}-airthings = "\
    python3-airthings-cloud (>=0.2.0) \
"

ALLOW_EMPTY:${PN}-airthings-ble = "1"
RDEPENDS:${PN}-airthings-ble = "\
    python3-airthings-ble (>=0.9.2) \
"

ALLOW_EMPTY:${PN}-airtouch4 = "1"
RDEPENDS:${PN}-airtouch4 = "\
    python3-airtouch4pyapi (>=1.0.5) \
"

ALLOW_EMPTY:${PN}-airtouch5 = "1"
RDEPENDS:${PN}-airtouch5 = "\
    python3-airtouch5py (>=0.3.0) \
"

ALLOW_EMPTY:${PN}-airvisual = "1"
RDEPENDS:${PN}-airvisual = "\
    python3-pyairvisual (>=2023.08.1) \
"

ALLOW_EMPTY:${PN}-airvisual-pro = "1"
RDEPENDS:${PN}-airvisual-pro = "\
    python3-pyairvisual (>=2023.08.1) \
"

ALLOW_EMPTY:${PN}-airzone = "1"
RDEPENDS:${PN}-airzone = "\
    python3-aioairzone (>=1.0.0) \
"

ALLOW_EMPTY:${PN}-airzone-cloud = "1"
RDEPENDS:${PN}-airzone-cloud = "\
    python3-aioairzone-cloud (>=0.7.2) \
"

ALLOW_EMPTY:${PN}-aladdin-connect = "1"
RDEPENDS:${PN}-aladdin-connect = "\
    python3-genie-partner-sdk (>=1.0.11) \
"

ALLOW_EMPTY:${PN}-alarm-control-panel = "1"

ALLOW_EMPTY:${PN}-alarmdecoder = "1"
RDEPENDS:${PN}-alarmdecoder = "\
    python3-adext (>=0.4.4) \
"

ALLOW_EMPTY:${PN}-alert = "1"

ALLOW_EMPTY:${PN}-alexa = "1"

ALLOW_EMPTY:${PN}-alpha-vantage = "1"
RDEPENDS:${PN}-alpha-vantage = "\
    python3-alpha-vantage (>=2.3.1) \
"

ALLOW_EMPTY:${PN}-altruist = "1"
RDEPENDS:${PN}-altruist = "\
    python3-altruistclient (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-amazon-polly = "1"
RDEPENDS:${PN}-amazon-polly = "\
    python3-boto3 (>=1.37.1) \
"

ALLOW_EMPTY:${PN}-amberelectric = "1"
RDEPENDS:${PN}-amberelectric = "\
    python3-amberelectric (>=2.0.12) \
"

ALLOW_EMPTY:${PN}-ambient-network = "1"
RDEPENDS:${PN}-ambient-network = "\
    python3-aioambient (>=2024.08.0) \
"

ALLOW_EMPTY:${PN}-ambient-station = "1"
RDEPENDS:${PN}-ambient-station = "\
    python3-aioambient (>=2024.08.0) \
"

ALLOW_EMPTY:${PN}-amcrest = "1"
RDEPENDS:${PN}-amcrest = "\
    python3-amcrest (>=1.9.9) \
"

ALLOW_EMPTY:${PN}-amp-motorization = "1"

ALLOW_EMPTY:${PN}-ampio = "1"
RDEPENDS:${PN}-ampio = "\
    python3-asmog (>=0.0.6) \
"

ALLOW_EMPTY:${PN}-analytics = "1"

ALLOW_EMPTY:${PN}-analytics-insights = "1"
RDEPENDS:${PN}-analytics-insights = "\
    python3-python-homeassistant-analytics (>=0.9.0) \
"

ALLOW_EMPTY:${PN}-android-ip-webcam = "1"
RDEPENDS:${PN}-android-ip-webcam = "\
    python3-pydroid-ipcam (>=3.0.0) \
"

ALLOW_EMPTY:${PN}-androidtv = "1"
RDEPENDS:${PN}-androidtv = "\
    python3-adb-shell (>=0.4.4) \
    python3-androidtv (>=0.0.75) \
"

ALLOW_EMPTY:${PN}-androidtv-remote = "1"
RDEPENDS:${PN}-androidtv-remote = "\
    python3-androidtvremote2 (>=0.2.3) \
"

ALLOW_EMPTY:${PN}-anel-pwrctrl = "1"
RDEPENDS:${PN}-anel-pwrctrl = "\
    python3-anel-pwrctrl-homeassistant (>=0.0.1.dev2) \
"

ALLOW_EMPTY:${PN}-anova = "1"
RDEPENDS:${PN}-anova = "\
    python3-anova-wifi (>=0.17.0) \
"

ALLOW_EMPTY:${PN}-anthemav = "1"
RDEPENDS:${PN}-anthemav = "\
    python3-anthemav (>=1.4.1) \
"

ALLOW_EMPTY:${PN}-anthropic = "1"
RDEPENDS:${PN}-anthropic = "\
    python3-anthropic (>=0.62.0) \
"

ALLOW_EMPTY:${PN}-anwb-energie = "1"

ALLOW_EMPTY:${PN}-aosmith = "1"
RDEPENDS:${PN}-aosmith = "\
    python3-py-aosmith (>=1.0.12) \
"

ALLOW_EMPTY:${PN}-apache-kafka = "1"
RDEPENDS:${PN}-apache-kafka = "\
    python3-aiokafka (>=0.10.0) \
"

ALLOW_EMPTY:${PN}-apcupsd = "1"
RDEPENDS:${PN}-apcupsd = "\
    python3-aioapcaccess (>=0.4.2) \
"

ALLOW_EMPTY:${PN}-api = "1"

ALLOW_EMPTY:${PN}-apollo-automation = "1"

ALLOW_EMPTY:${PN}-appalachianpower = "1"

ALLOW_EMPTY:${PN}-apple-tv = "1"
RDEPENDS:${PN}-apple-tv = "\
    python3-pyatv (>=0.16.1) \
"

ALLOW_EMPTY:${PN}-application-credentials = "1"

ALLOW_EMPTY:${PN}-aprilaire = "1"
RDEPENDS:${PN}-aprilaire = "\
    python3-pyaprilaire (>=0.9.1) \
"

ALLOW_EMPTY:${PN}-aprs = "1"
RDEPENDS:${PN}-aprs = "\
    python3-aprslib (>=0.7.2) \
    python3-geopy (>=2.3.0) \
"

ALLOW_EMPTY:${PN}-apsystems = "1"
RDEPENDS:${PN}-apsystems = "\
    python3-apsystems-ez1 (>=2.7.0) \
"

ALLOW_EMPTY:${PN}-aqualogic = "1"
RDEPENDS:${PN}-aqualogic = "\
    python3-aqualogic (>=2.6) \
"

ALLOW_EMPTY:${PN}-aquostv = "1"
RDEPENDS:${PN}-aquostv = "\
    python3-sharp-aquos-rc (>=0.3.2) \
"

ALLOW_EMPTY:${PN}-aranet = "1"
RDEPENDS:${PN}-aranet = "\
    python3-aranet4 (>=2.5.1) \
"

ALLOW_EMPTY:${PN}-arcam-fmj = "1"
RDEPENDS:${PN}-arcam-fmj = "\
    python3-arcam-fmj (>=1.8.2) \
"

ALLOW_EMPTY:${PN}-arest = "1"

ALLOW_EMPTY:${PN}-arris-tg2492lg = "1"
RDEPENDS:${PN}-arris-tg2492lg = "\
    python3-arris-tg2492lg (>=2.2.0) \
"

ALLOW_EMPTY:${PN}-artsound = "1"

ALLOW_EMPTY:${PN}-aruba = "1"
RDEPENDS:${PN}-aruba = "\
    python3-pexpect (>=4.9.0) \
"

ALLOW_EMPTY:${PN}-arve = "1"
RDEPENDS:${PN}-arve = "\
    python3-asyncarve (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-arwn = "1"

ALLOW_EMPTY:${PN}-aseko-pool-live = "1"
RDEPENDS:${PN}-aseko-pool-live = "\
    python3-aioaseko (>=1.0.0) \
"

ALLOW_EMPTY:${PN}-assist-pipeline = "1"
RDEPENDS:${PN}-assist-pipeline = "\
    python3-pymicro-vad (>=1.0.1) \
    python3-pyspeex-noise (>=1.0.2) \
"

ALLOW_EMPTY:${PN}-assist-satellite = "1"
RDEPENDS:${PN}-assist-satellite = "\
    python3-hassil (>=3.5.0) \
"

ALLOW_EMPTY:${PN}-asuswrt = "1"
RDEPENDS:${PN}-asuswrt = "\
    python3-aioasuswrt (>=1.4.0) \
    python3-asusrouter (>=1.20.1) \
"

ALLOW_EMPTY:${PN}-atag = "1"
RDEPENDS:${PN}-atag = "\
    python3-pyatag (>=0.3.5.3) \
"

ALLOW_EMPTY:${PN}-aten-pe = "1"
RDEPENDS:${PN}-aten-pe = "\
    python3-atenpdu (>=0.3.2) \
"

ALLOW_EMPTY:${PN}-atlanticcityelectric = "1"

ALLOW_EMPTY:${PN}-atome = "1"
RDEPENDS:${PN}-atome = "\
    python3-pyatome (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-august = "1"
RDEPENDS:${PN}-august = "\
    python3-yalexs (>=9.0.1) \
    python3-yalexs-ble (>=3.1.2) \
"

ALLOW_EMPTY:${PN}-august-ble = "1"

ALLOW_EMPTY:${PN}-aurora = "1"
RDEPENDS:${PN}-aurora = "\
    python3-auroranoaa (>=0.0.5) \
"

ALLOW_EMPTY:${PN}-aurora-abb-powerone = "1"
RDEPENDS:${PN}-aurora-abb-powerone = "\
    python3-aurorapy (>=0.2.7) \
"

ALLOW_EMPTY:${PN}-aussie-broadband = "1"
RDEPENDS:${PN}-aussie-broadband = "\
    python3-pyaussiebb (>=0.1.5) \
"

ALLOW_EMPTY:${PN}-autarco = "1"
RDEPENDS:${PN}-autarco = "\
    python3-autarco (>=3.1.0) \
"

ALLOW_EMPTY:${PN}-auth = "1"

ALLOW_EMPTY:${PN}-automation = "1"

ALLOW_EMPTY:${PN}-avea = "1"
RDEPENDS:${PN}-avea = "\
    python3-avea (>=1.5.1) \
"

ALLOW_EMPTY:${PN}-avion = "1"
RDEPENDS:${PN}-avion = "\
    python3-avion (>=0.10) \
"

ALLOW_EMPTY:${PN}-awair = "1"
RDEPENDS:${PN}-awair = "\
    python3-python-awair (>=0.2.4) \
"

ALLOW_EMPTY:${PN}-aws = "1"
RDEPENDS:${PN}-aws = "\
    python3-aiobotocore (>=2.21.1) \
    python3-botocore (>=1.37.1) \
"

ALLOW_EMPTY:${PN}-aws-s3 = "1"
RDEPENDS:${PN}-aws-s3 = "\
    python3-aiobotocore (>=2.21.1) \
"

ALLOW_EMPTY:${PN}-axis = "1"
RDEPENDS:${PN}-axis = "\
    python3-axis (>=65) \
"

ALLOW_EMPTY:${PN}-azure-data-explorer = "1"
RDEPENDS:${PN}-azure-data-explorer = "\
    python3-azure-kusto-ingest (>=4.5.1) \
    python3-azure-kusto-data (>=4.5.1) \
"

ALLOW_EMPTY:${PN}-azure-devops = "1"
RDEPENDS:${PN}-azure-devops = "\
    python3-aioazuredevops (>=2.2.2) \
"

ALLOW_EMPTY:${PN}-azure-event-hub = "1"
RDEPENDS:${PN}-azure-event-hub = "\
    python3-azure-eventhub (>=5.11.1) \
"

ALLOW_EMPTY:${PN}-azure-service-bus = "1"
RDEPENDS:${PN}-azure-service-bus = "\
    python3-azure-servicebus (>=7.10.0) \
"

ALLOW_EMPTY:${PN}-azure-storage = "1"
RDEPENDS:${PN}-azure-storage = "\
    python3-azure-storage-blob (>=12.24.0) \
"

ALLOW_EMPTY:${PN}-backup = "1"
RDEPENDS:${PN}-backup = "\
    python3-cronsim (>=2.6) \
    python3-securetar (>=2025.2.1) \
"

ALLOW_EMPTY:${PN}-baf = "1"
RDEPENDS:${PN}-baf = "\
    python3-aiobafi6 (>=0.9.0) \
"

ALLOW_EMPTY:${PN}-baidu = "1"
RDEPENDS:${PN}-baidu = "\
    python3-baidu-aip (>=1.6.6) \
"

ALLOW_EMPTY:${PN}-balay = "1"

ALLOW_EMPTY:${PN}-balboa = "1"
RDEPENDS:${PN}-balboa = "\
    python3-pybalboa (>=1.1.3) \
"

ALLOW_EMPTY:${PN}-bang-olufsen = "1"
RDEPENDS:${PN}-bang-olufsen = "\
    python3-mozart-api (>=4.1.1.116.4) \
"

ALLOW_EMPTY:${PN}-bauknecht = "1"

ALLOW_EMPTY:${PN}-bayesian = "1"

ALLOW_EMPTY:${PN}-bbox = "1"
RDEPENDS:${PN}-bbox = "\
    python3-pybbox (>=0.0.5-alpha) \
"

ALLOW_EMPTY:${PN}-beewi-smartclim = "1"
RDEPENDS:${PN}-beewi-smartclim = "\
    python3-beewi-smartclim (>=0.0.10) \
"

ALLOW_EMPTY:${PN}-bge = "1"

ALLOW_EMPTY:${PN}-binary-sensor = "1"

ALLOW_EMPTY:${PN}-bitcoin = "1"
RDEPENDS:${PN}-bitcoin = "\
    python3-blockchain (>=1.4.4) \
"

ALLOW_EMPTY:${PN}-bizkaibus = "1"
RDEPENDS:${PN}-bizkaibus = "\
    python3-bizkaibus (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-blackbird = "1"
RDEPENDS:${PN}-blackbird = "\
    python3-pyblackbird (>=0.6) \
"

ALLOW_EMPTY:${PN}-blebox = "1"
RDEPENDS:${PN}-blebox = "\
    python3-blebox-uniapi (>=2.5.0) \
"

ALLOW_EMPTY:${PN}-blink = "1"
RDEPENDS:${PN}-blink = "\
    python3-blinkpy (>=0.23.0) \
"

ALLOW_EMPTY:${PN}-blinksticklight = "1"
RDEPENDS:${PN}-blinksticklight = "\
    python3-blinkstick (>=1.2.0) \
"

ALLOW_EMPTY:${PN}-bliss-automation = "1"

ALLOW_EMPTY:${PN}-bloc-blinds = "1"

ALLOW_EMPTY:${PN}-blockchain = "1"
RDEPENDS:${PN}-blockchain = "\
    python3-bluecurrent-api (>=1.3.1) \
"

ALLOW_EMPTY:${PN}-blue-current = "1"
RDEPENDS:${PN}-blue-current = "\
    python3-python-blockchain-api (>=0.0.2) \
"

ALLOW_EMPTY:${PN}-bluemaestro = "1"
RDEPENDS:${PN}-bluemaestro = "\
    python3-bluemaestro-ble (>=0.4.1) \
"

ALLOW_EMPTY:${PN}-blueprint = "1"

ALLOW_EMPTY:${PN}-bluesound = "1"
RDEPENDS:${PN}-bluesound = "\
    python3-pyblu (>=2.0.4) \
"

# python3-dbus-fast (>=2.44.3)
ALLOW_EMPTY:${PN}-bluetooth = "1"
RDEPENDS:${PN}-bluetooth = "\
    python3-bleak (>=1.0.1) \
    python3-bleak-retry-connector (>=4.4.3) \
    python3-bluetooth-adapters (>=2.1.0) \
    python3-bluetooth-auto-recovery (>=1.5.2) \
    python3-bluetooth-data-tools (>=1.28.2) \
    python3-dbus-fast (>=2.44.1) \
    python3-habluetooth (>=5.6.4) \
"

ALLOW_EMPTY:${PN}-bluetooth-adapters = "1"

ALLOW_EMPTY:${PN}-bluetooth-le-tracker = "1"

ALLOW_EMPTY:${PN}-bmw-connected-drive = "1"
RDEPENDS:${PN}-bmw-connected-drive = "\
    python3-bimmer-connected (>=0.17.3) \
"

ALLOW_EMPTY:${PN}-bond = "1"
RDEPENDS:${PN}-bond = "\
    python3-bosch-alarm-mode2 (>=0.4.6) \
"

ALLOW_EMPTY:${PN}-bosch-alarm = "1"
RDEPENDS:${PN}-bosch-alarm = "\
    python3-bond-async (>=0.2.1) \
"

ALLOW_EMPTY:${PN}-bosch-shc = "1"
RDEPENDS:${PN}-bosch-shc = "\
    python3-boschshcpy (>=0.2.107) \
"

ALLOW_EMPTY:${PN}-brands = "1"

ALLOW_EMPTY:${PN}-brandt = "1"

ALLOW_EMPTY:${PN}-braviatv = "1"
RDEPENDS:${PN}-braviatv = "\
    python3-pybravia (>=0.3.4) \
"

ALLOW_EMPTY:${PN}-brel-home = "1"

ALLOW_EMPTY:${PN}-bring = "1"
RDEPENDS:${PN}-bring = "\
    python3-bring-api (>=1.1.0) \
"

ALLOW_EMPTY:${PN}-broadlink = "1"
RDEPENDS:${PN}-broadlink = "\
    python3-broadlink (>=0.19.0) \
"

ALLOW_EMPTY:${PN}-brother = "1"
RDEPENDS:${PN}-brother = "\
    python3-brother (>=5.0.1) \
"

ALLOW_EMPTY:${PN}-brottsplatskartan = "1"
RDEPENDS:${PN}-brottsplatskartan = "\
    python3-brottsplatskartan (>=1.0.5) \
"

ALLOW_EMPTY:${PN}-browser = "1"

ALLOW_EMPTY:${PN}-brunt = "1"
RDEPENDS:${PN}-brunt = "\
    python3-brunt (>=1.2.0) \
"

ALLOW_EMPTY:${PN}-bryant-evolution = "1"
RDEPENDS:${PN}-bryant-evolution = "\
    python3-evolutionhttp (>=0.0.18) \
"

ALLOW_EMPTY:${PN}-bsblan = "1"
RDEPENDS:${PN}-bsblan = "\
    python3-python-bsblan (>=2.1.0) \
"

ALLOW_EMPTY:${PN}-bswitch = "1"

ALLOW_EMPTY:${PN}-bt-home-hub-5 = "1"
RDEPENDS:${PN}-bt-home-hub-5 = "\
    python3-bthomehub5-devicelist (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-bt-smarthub = "1"
RDEPENDS:${PN}-bt-smarthub = "\
    python3-btsmarthub-devicelist (>=0.2.3) \
"

ALLOW_EMPTY:${PN}-bthome = "1"
RDEPENDS:${PN}-bthome = "\
    python3-bthome-ble (>=3.13.1) \
"

ALLOW_EMPTY:${PN}-bticino = "1"

ALLOW_EMPTY:${PN}-bubendorff = "1"

ALLOW_EMPTY:${PN}-buienradar = "1"
RDEPENDS:${PN}-buienradar = "\
    python3-buienradar (>=1.0.6) \
"

ALLOW_EMPTY:${PN}-burbank-water-and-power = "1"

ALLOW_EMPTY:${PN}-button = "1"

ALLOW_EMPTY:${PN}-caldav = "1"
RDEPENDS:${PN}-caldav = "\
    python3-caldav (>=1.6.0) \
    python3-icalendar (>=6.3.1) \
"

ALLOW_EMPTY:${PN}-calendar = "1"

ALLOW_EMPTY:${PN}-cambridge-audio = "1"
RDEPENDS:${PN}-cambridge-audio = "\
    python3-aiostreammagic (>=2.11.0) \
"

ALLOW_EMPTY:${PN}-camera = "1"
RDEPENDS:${PN}-camera = "\
    python3-pyturbojpeg (>=1.8.0) \
"

ALLOW_EMPTY:${PN}-canary = "1"
RDEPENDS:${PN}-canary = "\
    python3-py-canary (>=0.5.4) \
"

# python3-pychromecast (>= 14.0.9)
ALLOW_EMPTY:${PN}-cast = "1"
RDEPENDS:${PN}-cast = "\
    python3-pychromecast (>=14.0.7) \
"

ALLOW_EMPTY:${PN}-ccm15 = "1"
RDEPENDS:${PN}-ccm15 = "\
    python3-py-ccm15 (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-cert-expiry = "1"

ALLOW_EMPTY:${PN}-chacon-dio = "1"
RDEPENDS:${PN}-chacon-dio = "\
    python3-dio-chacon-wifi-api (>=1.2.2) \
"

ALLOW_EMPTY:${PN}-channels = "1"
RDEPENDS:${PN}-channels = "\
    python3-pychannels (>=1.2.3) \
"

ALLOW_EMPTY:${PN}-cisco-ios = "1"
RDEPENDS:${PN}-cisco-ios = "\
    python3-pexpect (>=4.9.0) \
"

ALLOW_EMPTY:${PN}-cisco-mobility-express = "1"
RDEPENDS:${PN}-cisco-mobility-express = "\
    python3-ciscomobilityexpress (>=0.3.9) \
"

ALLOW_EMPTY:${PN}-cisco-webex-teams = "1"
RDEPENDS:${PN}-cisco-webex-teams = "\
    python3-webexpythonsdk (>=2.0.1) \
"

ALLOW_EMPTY:${PN}-clementine = "1"
RDEPENDS:${PN}-clementine = "\
    python3-python-clementine-remote (>=1.0.1) \
"

ALLOW_EMPTY:${PN}-clickatell = "1"

ALLOW_EMPTY:${PN}-clicksend = "1"

ALLOW_EMPTY:${PN}-clicksend-tts = "1"

ALLOW_EMPTY:${PN}-climate = "1"

ALLOW_EMPTY:${PN}-cloud = "1"
RDEPENDS:${PN}-cloud = "\
    python3-hass-nabucasa (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-cloudflare = "1"
RDEPENDS:${PN}-cloudflare = "\
    python3-pycfdns (>=3.0.0) \
"

ALLOW_EMPTY:${PN}-cloudflare-r2 = "1"
RDEPENDS:${PN}-cloudflare-r2 = "\
    python3-aiobotocore (>=2.21.1) \
"

ALLOW_EMPTY:${PN}-cmus = "1"
RDEPENDS:${PN}-cmus = "\
    python3-pycmus (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-co2signal = "1"
RDEPENDS:${PN}-co2signal = "\
    python3-aioelectricitymaps (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-coautilities = "1"

ALLOW_EMPTY:${PN}-coinbase = "1"
RDEPENDS:${PN}-coinbase = "\
    python3-coinbase (>=2.1.0) \
    python3-coinbase-advanced-py (>=1.2.2) \
"

ALLOW_EMPTY:${PN}-color-extractor = "1"
RDEPENDS:${PN}-color-extractor = "\
    python3-colorthief (>=0.2.1) \
"

ALLOW_EMPTY:${PN}-comed = "1"

ALLOW_EMPTY:${PN}-comed-hourly-pricing = "1"

ALLOW_EMPTY:${PN}-comelit = "1"
RDEPENDS:${PN}-comelit = "\
    python3-aiocomelit (>=0.12.3) \
"

ALLOW_EMPTY:${PN}-comfoconnect = "1"
RDEPENDS:${PN}-comfoconnect = "\
    python3-pycomfoconnect (>=0.5.1) \
"

ALLOW_EMPTY:${PN}-command-line = "1"
RDEPENDS:${PN}-command-line = "\
    python3-jsonpath (>=0.82.2) \
"

ALLOW_EMPTY:${PN}-compensation = "1"
RDEPENDS:${PN}-compensation = "\
    python3-numpy (>=2.3.2) \
"

ALLOW_EMPTY:${PN}-concord232 = "1"
RDEPENDS:${PN}-concord232 = "\
    python3-concord232 (>=0.15.1) \
"

ALLOW_EMPTY:${PN}-coned = "1"

ALLOW_EMPTY:${PN}-config = "1"

ALLOW_EMPTY:${PN}-configurator = "1"

ALLOW_EMPTY:${PN}-constructa = "1"

ALLOW_EMPTY:${PN}-control4 = "1"
RDEPENDS:${PN}-control4 = "\
    python3-pycontrol4 (>=1.2.0) \
"

ALLOW_EMPTY:${PN}-conversation = "1"
RDEPENDS:${PN}-conversation = "\
    python3-hassil (>=3.2.0) \
    python3-home-assistant-intents (>=2025.9.3) \
"

ALLOW_EMPTY:${PN}-cookidoo = "1"
RDEPENDS:${PN}-cookidoo = "\
    python3-cookidoo-api (>=0.14.0) \
"

ALLOW_EMPTY:${PN}-coolmaster = "1"
RDEPENDS:${PN}-coolmaster = "\
    python3-pycoolmasternet-async (>=0.2.2) \
"

ALLOW_EMPTY:${PN}-cosori = "1"

ALLOW_EMPTY:${PN}-counter = "1"

ALLOW_EMPTY:${PN}-cover = "1"

ALLOW_EMPTY:${PN}-cozytouch = "1"

ALLOW_EMPTY:${PN}-cppm-tracker = "1"
RDEPENDS:${PN}-cppm-tracker = "\
    python3-clearpasspy (>=1.0.2) \
"

ALLOW_EMPTY:${PN}-cpuspeed = "1"
RDEPENDS:${PN}-cpuspeed = "\
    python3-py-cpuinfo (>=9.0.0) \
"

ALLOW_EMPTY:${PN}-cribl = "1"

ALLOW_EMPTY:${PN}-crownstone = "1"
RDEPENDS:${PN}-crownstone = "\
    python3-crownstone-cloud (>=1.4.11) \
    python3-crownstone-sse (>=2.0.5) \
    python3-crownstone-uart (>=2.1.0) \
    python3-pyserial (>=3.5) \
"

ALLOW_EMPTY:${PN}-currencylayer = "1"

ALLOW_EMPTY:${PN}-dacia = "1"

ALLOW_EMPTY:${PN}-daikin = "1"
RDEPENDS:${PN}-daikin = "\
    python3-pydaikin (>=2.16.0) \
"

ALLOW_EMPTY:${PN}-danfoss-air = "1"
RDEPENDS:${PN}-danfoss-air = "\
    python3-pydanfossair (>=0.1.0) \
"

ALLOW_EMPTY:${PN}-datadog = "1"
RDEPENDS:${PN}-datadog = "\
    python3-datadog (>=0.52.0) \
"

ALLOW_EMPTY:${PN}-date = "1"

ALLOW_EMPTY:${PN}-datetime = "1"

ALLOW_EMPTY:${PN}-ddwrt = "1"

ALLOW_EMPTY:${PN}-deako = "1"
RDEPENDS:${PN}-deako = "\
    python3-pydeako (>=0.6.0) \
"

ALLOW_EMPTY:${PN}-debugpy = "1"
RDEPENDS:${PN}-debugpy = "\
    python3-debugpy (>=1.8.14) \
"

ALLOW_EMPTY:${PN}-deconz = "1"
RDEPENDS:${PN}-deconz = "\
    python3-pydeconz (>=120) \
"

ALLOW_EMPTY:${PN}-decora-wifi = "1"
RDEPENDS:${PN}-decora-wifi = "\
    python3-decora-wifi (>=1.4) \
"

ALLOW_EMPTY:${PN}-decorquip = "1"

ALLOW_EMPTY:${PN}-default-config = "1"

ALLOW_EMPTY:${PN}-delijn = "1"
RDEPENDS:${PN}-delijn = "\
    python3-pydelijn (>=1.1.0) \
"

ALLOW_EMPTY:${PN}-delmarva = "1"

ALLOW_EMPTY:${PN}-deluge = "1"
RDEPENDS:${PN}-deluge = "\
    python3-deluge-client (>=1.10.2) \
"

ALLOW_EMPTY:${PN}-demo = "1"

ALLOW_EMPTY:${PN}-denon = "1"

ALLOW_EMPTY:${PN}-denonavr = "1"
RDEPENDS:${PN}-denonavr = "\
    python3-denonavr (>=1.1.2) \
"

ALLOW_EMPTY:${PN}-derivative = "1"

ALLOW_EMPTY:${PN}-devialet = "1"
RDEPENDS:${PN}-devialet = "\
    python3-devialet (>=1.5.7) \
"

ALLOW_EMPTY:${PN}-device-automation = "1"

ALLOW_EMPTY:${PN}-device-sun-light-trigger = "1"

ALLOW_EMPTY:${PN}-device-tracker = "1"

ALLOW_EMPTY:${PN}-devolo-home-control = "1"
RDEPENDS:${PN}-devolo-home-control = "\
    python3-devolo-home-control-api (>=0.19.0) \
"

ALLOW_EMPTY:${PN}-devolo-home-network = "1"
RDEPENDS:${PN}-devolo-home-network = "\
    python3-devolo-plc-api (>=1.5.1) \
"

ALLOW_EMPTY:${PN}-dexcom = "1"
RDEPENDS:${PN}-dexcom = "\
    python3-pydexcom (>=0.2.3) \
"

ALLOW_EMPTY:${PN}-dhcp = "1"
RDEPENDS:${PN}-dhcp = "\
    python3-aiodhcpwatcher (>=1.2.1) \
    python3-aiodiscover (>=2.7.1) \
    python3-cached-ipaddress (>=0.10.0) \
"

ALLOW_EMPTY:${PN}-diagnostics = "1"

ALLOW_EMPTY:${PN}-dialogflow = "1"

ALLOW_EMPTY:${PN}-diaz = "1"

ALLOW_EMPTY:${PN}-digital-loggers = "1"

ALLOW_EMPTY:${PN}-digital-ocean = "1"
RDEPENDS:${PN}-digital-ocean = "\
    python3-python-digitalocean (>=1.13.2) \
"

ALLOW_EMPTY:${PN}-directv = "1"
RDEPENDS:${PN}-directv = "\
    python3-directv (>=0.4.0) \
"

ALLOW_EMPTY:${PN}-discogs = "1"
RDEPENDS:${PN}-discogs = "\
    python3-discogs-client (>=2.3.0) \
"

ALLOW_EMPTY:${PN}-discord = "1"
RDEPENDS:${PN}-discord = "\
    python3-nextcord (>=3.1.0) \
"

ALLOW_EMPTY:${PN}-discovergy = "1"
RDEPENDS:${PN}-discovergy = "\
    python3-pydiscovergy (>=3.0.2) \
"

ALLOW_EMPTY:${PN}-dlink = "1"
RDEPENDS:${PN}-dlink = "\
    python3-pyw215 (>=0.8.0) \
"

ALLOW_EMPTY:${PN}-dlna-dmr = "1"
RDEPENDS:${PN}-dlna-dmr = "\
    python3-async-upnp-client (>=0.45.0) \
    python3-getmac (>=0.9.5) \
"

ALLOW_EMPTY:${PN}-dlna-dms = "1"
RDEPENDS:${PN}-dlna-dms = "\
    python3-async-upnp-client (>=0.45.0) \
"

ALLOW_EMPTY:${PN}-dnsip = "1"
RDEPENDS:${PN}-dnsip = "\
    python3-aiodns (>=3.5.0) \
"

ALLOW_EMPTY:${PN}-doods = "1"
RDEPENDS:${PN}-doods = "\
    python3-pydoods (>=1.0.2) \
    python3-pillow (>=11.3.0) \
"

ALLOW_EMPTY:${PN}-doorbird = "1"
RDEPENDS:${PN}-doorbird = "\
    python3-doorbirdpy (>=3.0.8) \
"

ALLOW_EMPTY:${PN}-dooya = "1"

ALLOW_EMPTY:${PN}-dormakaba-dkey = "1"
RDEPENDS:${PN}-dormakaba-dkey = "\
    python3-py-dormakaba-dkey (>=1.0.6) \
"

ALLOW_EMPTY:${PN}-dovado = "1"
RDEPENDS:${PN}-dovado = "\
    python3-dovado (>=0.4.1) \
"

ALLOW_EMPTY:${PN}-downloader = "1"

ALLOW_EMPTY:${PN}-dremel-3d-printer = "1"
RDEPENDS:${PN}-dremel-3d-printer = "\
    python3-dremel3dpy (>=2.1.1) \
"

ALLOW_EMPTY:${PN}-drop-connect = "1"
RDEPENDS:${PN}-drop-connect = "\
    python3-dropmqttapi (>=1.0.3) \
"

ALLOW_EMPTY:${PN}-dsmr = "1"
RDEPENDS:${PN}-dsmr = "\
    python3-dsmr-parser (>=1.4.3) \
"

ALLOW_EMPTY:${PN}-dsmr-reader = "1"

ALLOW_EMPTY:${PN}-dublin-bus-transport = "1"

ALLOW_EMPTY:${PN}-duckdns = "1"

ALLOW_EMPTY:${PN}-duke-energy = "1"
RDEPENDS:${PN}-duke-energy = "\
    python3-aiodukeenergy (>=0.3.0) \
"

ALLOW_EMPTY:${PN}-dunehd = "1"
RDEPENDS:${PN}-dunehd = "\
    python3-pdunehd (>=1.3.2) \
"

ALLOW_EMPTY:${PN}-duotecno = "1"
RDEPENDS:${PN}-duotecno = "\
    python3-pyduotecno (>=2024.10.1) \
"

ALLOW_EMPTY:${PN}-duquesne-light = "1"

ALLOW_EMPTY:${PN}-dwd-weather-warnings = "1"
RDEPENDS:${PN}-dwd-weather-warnings = "\
    python3-dwdwfsapi (>=1.0.7) \
"

ALLOW_EMPTY:${PN}-dynalite = "1"
RDEPENDS:${PN}-dynalite = "\
    python3-dynalite-devices (>=0.1.47) \
    python3-dynalite-panel (>=0.0.4) \
"

ALLOW_EMPTY:${PN}-eafm = "1"
RDEPENDS:${PN}-eafm = "\
    python3-aioeafm (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-eastron = "1"

ALLOW_EMPTY:${PN}-easyenergy = "1"
RDEPENDS:${PN}-easyenergy = "\
    python3-easyenergy (>=2.1.2) \
"

ALLOW_EMPTY:${PN}-ebox = "1"
RDEPENDS:${PN}-ebox = "\
    python3-pyebox (>=1.1.4) \
"

ALLOW_EMPTY:${PN}-ebusd = "1"
RDEPENDS:${PN}-ebusd = "\
    python3-ebusdpy (>=0.0.17) \
"

ALLOW_EMPTY:${PN}-ecoal-boiler = "1"
RDEPENDS:${PN}-ecoal-boiler = "\
    python3-ecoaliface (>=0.4.0) \
"

ALLOW_EMPTY:${PN}-ecobee = "1"
RDEPENDS:${PN}-ecobee = "\
    python3-python-ecobee-api (>=0.2.20) \
"

ALLOW_EMPTY:${PN}-ecoforest = "1"
RDEPENDS:${PN}-ecoforest = "\
    python3-pyecoforest (>=0.4.0) \
"

ALLOW_EMPTY:${PN}-econet = "1"
RDEPENDS:${PN}-econet = "\
    python3-pyeconet (>=0.1.28) \
"

ALLOW_EMPTY:${PN}-ecovacs = "1"
RDEPENDS:${PN}-ecovacs = "\
    python3-py-sucks (>=0.9.11) \
    python3-deebot-client (>=13.7.0) \
"

ALLOW_EMPTY:${PN}-ecowitt = "1"
RDEPENDS:${PN}-ecowitt = "\
    python3-aioecowitt (>=2025.9.1) \
"

ALLOW_EMPTY:${PN}-edimax = "1"
RDEPENDS:${PN}-edimax = "\
    python3-pyedimax (>=0.2.1) \
"

ALLOW_EMPTY:${PN}-edl21 = "1"
RDEPENDS:${PN}-edl21 = "\
    python3-pysml (>=0.1.5) \
"

ALLOW_EMPTY:${PN}-efergy = "1"
RDEPENDS:${PN}-efergy = "\
    python3-pyefergy (>=22.5.0) \
"

ALLOW_EMPTY:${PN}-egardia = "1"
RDEPENDS:${PN}-egardia = "\
    python3-pythonegardia (>=1.0.52) \
"

ALLOW_EMPTY:${PN}-eheimdigital = "1"
RDEPENDS:${PN}-eheimdigital = "\
    python3-eheimdigital (>=1.3.0) \
"

ALLOW_EMPTY:${PN}-eight-sleep = "1"

ALLOW_EMPTY:${PN}-electrasmart = "1"
RDEPENDS:${PN}-electrasmart = "\
    python3-pyelectra (>=1.2.4) \
"

ALLOW_EMPTY:${PN}-electric-kiwi = "1"
RDEPENDS:${PN}-electric-kiwi = "\
    python3-electrickiwi-api (>=0.9.14) \
"

ALLOW_EMPTY:${PN}-elevenlabs = "1"
RDEPENDS:${PN}-elevenlabs = "\
    python3-elevenlabs (>=2.3.0) \
"

ALLOW_EMPTY:${PN}-elgato = "1"
RDEPENDS:${PN}-elgato = "\
    python3-elgato (>=5.1.2) \
"

ALLOW_EMPTY:${PN}-eliqonline = "1"
RDEPENDS:${PN}-eliqonline = "\
    python3-eliqonline (>=1.2.2) \
"

ALLOW_EMPTY:${PN}-elkm1 = "1"
RDEPENDS:${PN}-elkm1 = "\
    python3-elkm1-lib (>=2.2.11) \
"

ALLOW_EMPTY:${PN}-elmax = "1"
RDEPENDS:${PN}-elmax = "\
    python3-elmax-api (>=0.0.6.4rc0) \
"

ALLOW_EMPTY:${PN}-elv = "1"
RDEPENDS:${PN}-elv = "\
    python3-pypca (>=0.0.7) \
"

ALLOW_EMPTY:${PN}-elvia = "1"
RDEPENDS:${PN}-elvia = "\
    python3-elvia (>=0.1.0) \
"

ALLOW_EMPTY:${PN}-emby = "1"
RDEPENDS:${PN}-emby = "\
    python3-pyemby (>=1.10) \
"

ALLOW_EMPTY:${PN}-emoncms = "1"
RDEPENDS:${PN}-emoncms = "\
    python3-pyemoncms (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-emoncms-history = "1"
RDEPENDS:${PN}-emoncms-history = "\
    python3-pyemoncms (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-emonitor = "1"
RDEPENDS:${PN}-emonitor = "\
    python3-aioemonitor (>=1.0.5) \
"

ALLOW_EMPTY:${PN}-emulated-hue = "1"

ALLOW_EMPTY:${PN}-emulated-kasa = "1"
RDEPENDS:${PN}-emulated-kasa = "\
    python3-sense-energy (>=0.13.8) \
"

ALLOW_EMPTY:${PN}-emulated-roku = "1"
RDEPENDS:${PN}-emulated-roku = "\
    python3-emulated-roku (>=0.3.0) \
"

ALLOW_EMPTY:${PN}-energenie-power-sockets = "1"
RDEPENDS:${PN}-energenie-power-sockets = "\
    python3-pyegps (>=0.2.5) \
"

ALLOW_EMPTY:${PN}-energie-vanons = "1"

ALLOW_EMPTY:${PN}-energy = "1"

ALLOW_EMPTY:${PN}-energyzero = "1"
RDEPENDS:${PN}-energyzero = "\
    python3-energyzero (>=2.1.1) \
"

ALLOW_EMPTY:${PN}-enigma2 = "1"
RDEPENDS:${PN}-enigma2 = "\
    python3-openwebifpy (>=4.3.1) \
"

ALLOW_EMPTY:${PN}-enocean = "1"
RDEPENDS:${PN}-enocean = "\
    python3-enocean (>=0.50) \
"

ALLOW_EMPTY:${PN}-enphase-envoy = "1"
RDEPENDS:${PN}-enphase-envoy = "\
    python3-pyenphase (>=2.3.0) \
"

ALLOW_EMPTY:${PN}-entur-public-transport = "1"
RDEPENDS:${PN}-entur-public-transport = "\
    python3-enturclient (>=0.2.4) \
"

ALLOW_EMPTY:${PN}-environment-canada = "1"
RDEPENDS:${PN}-environment-canada = "\
    python3-env-canada (>=0.12.4) \
"

ALLOW_EMPTY:${PN}-envisalink = "1"
RDEPENDS:${PN}-envisalink = "\
    python3-pyenvisalink (>=4.7) \
"

ALLOW_EMPTY:${PN}-ephember = "1"
RDEPENDS:${PN}-ephember = "\
    python3-pyephember2 (>=0.4.12) \
"

ALLOW_EMPTY:${PN}-epic-games-store = "1"
RDEPENDS:${PN}-epic-games-store = "\
    python3-epicstore-api (>=0.1.7) \
"

ALLOW_EMPTY:${PN}-epion = "1"
RDEPENDS:${PN}-epion = "\
    python3-epion (>=0.0.3) \
"

ALLOW_EMPTY:${PN}-epson = "1"
RDEPENDS:${PN}-epson = "\
    python3-epson-projector (>=0.5.1) \
"

ALLOW_EMPTY:${PN}-eq3btsmart = "1"
RDEPENDS:${PN}-eq3btsmart = "\
    python3-eq3btsmart (>=2.1.0) \
    python3-bleak-esphome (>=3.3.0) \
"

ALLOW_EMPTY:${PN}-escea = "1"
RDEPENDS:${PN}-escea = "\
    python3-pescea (>=1.0.12) \
"

ALLOW_EMPTY:${PN}-esera-onewire = "1"

ALLOW_EMPTY:${PN}-esphome = "1"
RDEPENDS:${PN}-esphome = "\
    python3-aioesphomeapi (>=39.0.1) \
    python3-esphome-dashboard-api (>=1.3.0) \
    python3-bleak-esphome (>=3.3.0) \
"

ALLOW_EMPTY:${PN}-etherscan = "1"
RDEPENDS:${PN}-etherscan = "\
    python3-python-etherscan-api (>=0.0.3) \
"

ALLOW_EMPTY:${PN}-eufy = "1"
RDEPENDS:${PN}-eufy = "\
    python3-lakeside (>=0.13) \
"

ALLOW_EMPTY:${PN}-eufylife-ble = "1"
RDEPENDS:${PN}-eufylife-ble = "\
    python3-eufylife-ble-client (>=0.1.8) \
"

ALLOW_EMPTY:${PN}-event = "1"

ALLOW_EMPTY:${PN}-evergy = "1"

ALLOW_EMPTY:${PN}-everlights = "1"
RDEPENDS:${PN}-everlights = "\
    python3-pyeverlights (>=0.1.0) \
"

ALLOW_EMPTY:${PN}-evil-genius-labs = "1"
RDEPENDS:${PN}-evil-genius-labs = "\
    python3-pyevilgenius (>=2.0.0) \
"

ALLOW_EMPTY:${PN}-evohome = "1"
RDEPENDS:${PN}-evohome = "\
    python3-evohome-async (>=1.0.5) \
"

ALLOW_EMPTY:${PN}-ezviz = "1"
RDEPENDS:${PN}-ezviz = "\
    python3-pyezvizapi (>=1.0.0.7) \
"

ALLOW_EMPTY:${PN}-faa-delays = "1"
RDEPENDS:${PN}-faa-delays = "\
    python3-faadelays (>=2023.9.1) \
"

ALLOW_EMPTY:${PN}-facebook = "1"

ALLOW_EMPTY:${PN}-fail2ban = "1"

ALLOW_EMPTY:${PN}-familyhub = "1"
RDEPENDS:${PN}-familyhub = "\
    python3-python-family-hub-local (>=0.0.2) \
"

ALLOW_EMPTY:${PN}-fan = "1"

ALLOW_EMPTY:${PN}-fastdotcom = "1"
RDEPENDS:${PN}-fastdotcom = "\
    python3-fastdotcom (>=0.0.3) \
"

ALLOW_EMPTY:${PN}-feedreader = "1"
RDEPENDS:${PN}-feedreader = "\
    python3-feedparser (>=6.0.11) \
"

ALLOW_EMPTY:${PN}-ffmpeg = "1"
RDEPENDS:${PN}-ffmpeg = "\
    python3-ha-ffmpeg (>=3.2.2) \
"

ALLOW_EMPTY:${PN}-ffmpeg-motion = "1"

ALLOW_EMPTY:${PN}-ffmpeg-noise = "1"

ALLOW_EMPTY:${PN}-fibaro = "1"
RDEPENDS:${PN}-fibaro = "\
    python3-pyfibaro (>=0.8.3) \
"

ALLOW_EMPTY:${PN}-fido = "1"
RDEPENDS:${PN}-fido = "\
    python3-pyfido (>=2.1.2) \
"

ALLOW_EMPTY:${PN}-file = "1"
RDEPENDS:${PN}-file = "\
    python3-file-read-backwards (>=2.0.0) \
"

ALLOW_EMPTY:${PN}-file-upload = "1"

ALLOW_EMPTY:${PN}-filesize = "1"

ALLOW_EMPTY:${PN}-filter = "1"

ALLOW_EMPTY:${PN}-fints = "1"
RDEPENDS:${PN}-fints = "\
    python3-fints (>=3.1.0) \
"

ALLOW_EMPTY:${PN}-fire-tv = "1"

ALLOW_EMPTY:${PN}-fireservicerota = "1"
RDEPENDS:${PN}-fireservicerota = "\
    python3-pyfireservicerota (>=0.0.46) \
"

ALLOW_EMPTY:${PN}-firmata = "1"
RDEPENDS:${PN}-firmata = "\
    python3-pymata-express (>=1.19) \
"

ALLOW_EMPTY:${PN}-fitbit = "1"
RDEPENDS:${PN}-fitbit = "\
    python3-fitbit (>=0.3.1) \
"

ALLOW_EMPTY:${PN}-fivem = "1"
RDEPENDS:${PN}-fivem = "\
    python3-fivem-api (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-fixer = "1"
RDEPENDS:${PN}-fixer = "\
    python3-fixerio (>=1.0.0) \
"

ALLOW_EMPTY:${PN}-fjaraskupan = "1"
RDEPENDS:${PN}-fjaraskupan = "\
    python3-fjaraskupan (>=2.3.2) \
"

ALLOW_EMPTY:${PN}-fleetgo = "1"
RDEPENDS:${PN}-fleetgo = "\
    python3-ritassist (>=0.9.2) \
"

ALLOW_EMPTY:${PN}-flexit = "1"

ALLOW_EMPTY:${PN}-flexit-bacnet = "1"
RDEPENDS:${PN}-flexit-bacnet = "\
    python3-flexit-bacnet (>=2.2.3) \
"

ALLOW_EMPTY:${PN}-flexom = "1"

ALLOW_EMPTY:${PN}-flic = "1"
RDEPENDS:${PN}-flic = "\
    python3-pyflic (>=2.0.4) \
"

ALLOW_EMPTY:${PN}-flipr = "1"
RDEPENDS:${PN}-flipr = "\
    python3-flipr-api (>=1.6.1) \
"

ALLOW_EMPTY:${PN}-flo = "1"
RDEPENDS:${PN}-flo = "\
    python3-aioflo (>=2021.11.0) \
"

ALLOW_EMPTY:${PN}-flock = "1"

ALLOW_EMPTY:${PN}-flume = "1"
RDEPENDS:${PN}-flume = "\
    python3-pyflume (>=0.6.5) \
"

ALLOW_EMPTY:${PN}-flux = "1"

ALLOW_EMPTY:${PN}-flux-led = "1"
RDEPENDS:${PN}-flux-led = "\
    python3-flux-led (>=1.2.0) \
"

ALLOW_EMPTY:${PN}-folder = "1"

ALLOW_EMPTY:${PN}-folder-watcher = "1"
RDEPENDS:${PN}-folder-watcher = "\
    python3-watchdog (>=6.0.0) \
"

ALLOW_EMPTY:${PN}-foobot = "1"
RDEPENDS:${PN}-foobot = "\
    python3-foobot-async (>=1.0.0) \
"

ALLOW_EMPTY:${PN}-forecast-solar = "1"
RDEPENDS:${PN}-forecast-solar = "\
    python3-forecast-solar (>=4.2.0) \
"

ALLOW_EMPTY:${PN}-forked-daapd = "1"
RDEPENDS:${PN}-forked-daapd = "\
    python3-pyforked-daapd (>=0.1.14) \
    python3-pylibrespot-java (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-fortios = "1"
RDEPENDS:${PN}-fortios = "\
    python3-fortiosapi (>=1.0.5) \
"

ALLOW_EMPTY:${PN}-foscam = "1"
RDEPENDS:${PN}-foscam = "\
    python3-libpyfoscamcgi (>=0.0.7) \
"

ALLOW_EMPTY:${PN}-foursquare = "1"

ALLOW_EMPTY:${PN}-frankever = "1"

ALLOW_EMPTY:${PN}-free-mobile = "1"
RDEPENDS:${PN}-free-mobile = "\
    python3-freesms (>=0.2.0) \
"

ALLOW_EMPTY:${PN}-freebox = "1"
RDEPENDS:${PN}-freebox = "\
    python3-freebox-api (>=1.2.2) \
"

ALLOW_EMPTY:${PN}-freedns = "1"

ALLOW_EMPTY:${PN}-freedompro = "1"
RDEPENDS:${PN}-freedompro = "\
    python3-pyfreedompro (>=1.1.0) \
"

ALLOW_EMPTY:${PN}-fritz = "1"
RDEPENDS:${PN}-fritz = "\
    python3-fritzconnection (>=1.14.0) \
    python3-xmltodict (>=0.13.0) \
"

ALLOW_EMPTY:${PN}-fritzbox = "1"
RDEPENDS:${PN}-fritzbox = "\
    python3-pyfritzhome (>=0.6.17) \
"

ALLOW_EMPTY:${PN}-fritzbox-callmonitor = "1"
RDEPENDS:${PN}-fritzbox-callmonitor = "\
    python3-fritzconnection (>=1.14.0) \
"

ALLOW_EMPTY:${PN}-fronius = "1"
RDEPENDS:${PN}-fronius = "\
    python3-pyfronius (>=0.8.0) \
"

ALLOW_EMPTY:${PN}-frontend = "1"
RDEPENDS:${PN}-frontend = "\
    python3-home-assistant-frontend (>=20250903.5) \
"

ALLOW_EMPTY:${PN}-frontier-silicon = "1"
RDEPENDS:${PN}-frontier-silicon = "\
    python3-afsapi (>=0.2.7) \
"

ALLOW_EMPTY:${PN}-fujitsu-anywair = "1"

ALLOW_EMPTY:${PN}-fujitsu-fglair = "1"
RDEPENDS:${PN}-fujitsu-fglair = "\
    python3-ayla-iot-unofficial (>=1.4.7) \
"

ALLOW_EMPTY:${PN}-fully-kiosk = "1"
RDEPENDS:${PN}-fully-kiosk = "\
    python3-python-fullykiosk (>=0.0.14) \
"

ALLOW_EMPTY:${PN}-futurenow = "1"
RDEPENDS:${PN}-futurenow = "\
    python3-pyfnip (>=0.2) \
"

ALLOW_EMPTY:${PN}-fyta = "1"
RDEPENDS:${PN}-fyta = "\
    python3-fyta-cli (>=0.7.2) \
"

ALLOW_EMPTY:${PN}-gaggenau = "1"

ALLOW_EMPTY:${PN}-garadget = "1"

ALLOW_EMPTY:${PN}-garages-amsterdam = "1"
RDEPENDS:${PN}-garages-amsterdam = "\
    python3-odp-amsterdam (>=6.1.2) \
"

ALLOW_EMPTY:${PN}-gardena-bluetooth = "1"
RDEPENDS:${PN}-gardena-bluetooth = "\
    python3-gardena-bluetooth (>=1.6.0) \
"

ALLOW_EMPTY:${PN}-gaviota = "1"

ALLOW_EMPTY:${PN}-gc100 = "1"
RDEPENDS:${PN}-gc100 = "\
    python3-python-gc100 (>=1.0.3a0) \
"

ALLOW_EMPTY:${PN}-gdacs = "1"
RDEPENDS:${PN}-gdacs = "\
    python3-aio-georss-gdacs (>=0.10) \
"

ALLOW_EMPTY:${PN}-generic = "1"
RDEPENDS:${PN}-generic = "\
    python3-av (>=13.1.0) \
    python3-pillow (>=11.3.0) \
"

ALLOW_EMPTY:${PN}-generic-hygrostat = "1"

ALLOW_EMPTY:${PN}-generic-thermostat = "1"

ALLOW_EMPTY:${PN}-geniushub = "1"
RDEPENDS:${PN}-geniushub = "\
    python3-geniushub-client (>=0.7.1) \
"

ALLOW_EMPTY:${PN}-geo-json-events = "1"
RDEPENDS:${PN}-geo-json-events = "\
    python3-aio-geojson-generic-client (>=0.5) \
"

ALLOW_EMPTY:${PN}-geo-location = "1"

ALLOW_EMPTY:${PN}-geo-rss-events = "1"
RDEPENDS:${PN}-geo-rss-events = "\
    python3-georss-generic-client (>=0.8) \
"

ALLOW_EMPTY:${PN}-geocaching = "1"
RDEPENDS:${PN}-geocaching = "\
    python3-geocachingapi (>=0.3.0) \
"

ALLOW_EMPTY:${PN}-geofency = "1"

ALLOW_EMPTY:${PN}-geonetnz-quakes = "1"
RDEPENDS:${PN}-geonetnz-quakes = "\
    python3-aio-geojson-geonetnz-quakes (>=0.16) \
"

ALLOW_EMPTY:${PN}-geonetnz-volcano = "1"
RDEPENDS:${PN}-geonetnz-volcano = "\
    python3-aio-geojson-geonetnz-volcano (>=0.9) \
"

ALLOW_EMPTY:${PN}-gios = "1"
RDEPENDS:${PN}-gios = "\
    python3-gios (>=6.1.2) \
"

ALLOW_EMPTY:${PN}-github = "1"
RDEPENDS:${PN}-github = "\
    python3-aiogithubapi (>=24.6.0) \
"

ALLOW_EMPTY:${PN}-gitlab-ci = "1"
RDEPENDS:${PN}-gitlab-ci = "\
    python3-python-gitlab (>=1.6.0) \
"

ALLOW_EMPTY:${PN}-gitter = "1"
RDEPENDS:${PN}-gitter = "\
    python3-gitterpy (>=0.1.7) \
"

ALLOW_EMPTY:${PN}-glances = "1"
RDEPENDS:${PN}-glances = "\
    python3-glances-api (>=0.8.0) \
"

ALLOW_EMPTY:${PN}-go2rtc = "1"
RDEPENDS:${PN}-go2rtc = "\
    python3-go2rtc-client (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-goalzero = "1"
RDEPENDS:${PN}-goalzero = "\
    python3-goalzero (>=0.2.2) \
"

ALLOW_EMPTY:${PN}-gogogate2 = "1"
RDEPENDS:${PN}-gogogate2 = "\
    python3-ismartgate (>=5.0.2) \
"

ALLOW_EMPTY:${PN}-goodwe = "1"
RDEPENDS:${PN}-goodwe = "\
    python3-goodwe (>=0.4.8) \
"

ALLOW_EMPTY:${PN}-google = "1"
RDEPENDS:${PN}-google = "\
    python3-gcal-sync (>=8.0.0) \
    python3-oauth2client (>=4.1.3) \
    python3-ical (>=11.0.0) \
"

ALLOW_EMPTY:${PN}-google-assistant = "1"

ALLOW_EMPTY:${PN}-google-assistant-sdk = "1"
RDEPENDS:${PN}-google-assistant-sdk = "\
    python3-gassist-text (>=0.0.14) \
"

ALLOW_EMPTY:${PN}-google-cloud = "1"
RDEPENDS:${PN}-google-cloud = "\
    python3-google-cloud-texttospeech (>=2.25.1) \
    python3-google-cloud-speech (>=2.31.1) \
"

ALLOW_EMPTY:${PN}-google-drive = "1"
RDEPENDS:${PN}-google-drive = "\
    python3-python-google-drive-api (>=0.1.0) \
"

ALLOW_EMPTY:${PN}-google-generative-ai-conversation = "1"
RDEPENDS:${PN}-google-generative-ai-conversation = "\
    python3-google-genai (>=1.29.0) \
"

ALLOW_EMPTY:${PN}-google-mail = "1"
RDEPENDS:${PN}-google-mail = "\
    python3-google-api-python-client (>=2.71.0) \
"

ALLOW_EMPTY:${PN}-google-maps = "1"
RDEPENDS:${PN}-google-maps = "\
    python3-locationsharinglib (>=5.0.1) \
"

ALLOW_EMPTY:${PN}-google-photos = "1"
RDEPENDS:${PN}-google-photos = "\
    python3-google-photos-library-api (>=0.12.1) \
"

ALLOW_EMPTY:${PN}-google-pubsub = "1"
RDEPENDS:${PN}-google-pubsub = "\
    python3-google-cloud-pubsub (>=2.29.0) \
"

ALLOW_EMPTY:${PN}-google-sheets = "1"
RDEPENDS:${PN}-google-sheets = "\
    python3-gspread (>=5.5.0) \
"

ALLOW_EMPTY:${PN}-google-tasks = "1"
RDEPENDS:${PN}-google-tasks = "\
    python3-google-api-python-client (>=2.71.0) \
"

ALLOW_EMPTY:${PN}-google-translate = "1"
RDEPENDS:${PN}-google-translate = "\
    python3-gtts (>=2.5.3) \
"

ALLOW_EMPTY:${PN}-google-travel-time = "1"
RDEPENDS:${PN}-google-travel-time = "\
    python3-google-maps-routing (>=0.6.15) \
"

ALLOW_EMPTY:${PN}-google-wifi = "1"

ALLOW_EMPTY:${PN}-govee-ble = "1"
RDEPENDS:${PN}-govee-ble = "\
    python3-govee-ble (>=0.44.0) \
"

ALLOW_EMPTY:${PN}-govee-light-local = "1"
RDEPENDS:${PN}-govee-light-local = "\
    python3-govee-local-api (>=2.1.0) \
"

ALLOW_EMPTY:${PN}-gpsd = "1"
RDEPENDS:${PN}-gpsd = "\
    python3-gps3 (>=0.33.3) \
"

ALLOW_EMPTY:${PN}-gpslogger = "1"

ALLOW_EMPTY:${PN}-graphite = "1"

ALLOW_EMPTY:${PN}-gree = "1"
RDEPENDS:${PN}-gree = "\
    python3-greeclimate (>=2.1.0) \
"

ALLOW_EMPTY:${PN}-greeneye-monitor = "1"
RDEPENDS:${PN}-greeneye-monitor = "\
    python3-greeneye-monitor (>=3.0.3) \
"

ALLOW_EMPTY:${PN}-greenwave = "1"
RDEPENDS:${PN}-greenwave = "\
    python3-greenwavereality (>=0.5.1) \
"

ALLOW_EMPTY:${PN}-group = "1"

ALLOW_EMPTY:${PN}-growatt-server = "1"
RDEPENDS:${PN}-growatt-server = "\
    python3-growattserver (>=1.7.1) \
"

ALLOW_EMPTY:${PN}-gtfs = "1"
RDEPENDS:${PN}-gtfs = "\
    python3-pygtfs (>=0.1.9) \
"

ALLOW_EMPTY:${PN}-guardian = "1"
RDEPENDS:${PN}-guardian = "\
    python3-aioguardian (>=2022.07.0) \
"

ALLOW_EMPTY:${PN}-hardkernel = "1"

ALLOW_EMPTY:${PN}-hardware = "1"
RDEPENDS:${PN}-hardware = "\
    python3-psutil-home-assistant (>=0.0.1) \
    python3-universal-silabs-flasher (>=0.0.25) \
    python3-ha-silabs-firmware-client (>=0.2.0) \
"

ALLOW_EMPTY:${PN}-harvey = "1"

ALLOW_EMPTY:${PN}-hassio = "1"
RDEPENDS:${PN}-hassio = "\
    python3-aiohasupervisor (>=0.3.3) \
"

ALLOW_EMPTY:${PN}-havana-shade = "1"

ALLOW_EMPTY:${PN}-haveibeenpwned = "1"

ALLOW_EMPTY:${PN}-hddtemp = "1"

ALLOW_EMPTY:${PN}-heicko = "1"

ALLOW_EMPTY:${PN}-heiwa = "1"

ALLOW_EMPTY:${PN}-hexaom = "1"

ALLOW_EMPTY:${PN}-hi-kumo = "1"

ALLOW_EMPTY:${PN}-history = "1"

ALLOW_EMPTY:${PN}-history-stats = "1"

ALLOW_EMPTY:${PN}-hitron-coda = "1"

ALLOW_EMPTY:${PN}-home-plus-control = "1"

ALLOW_EMPTY:${PN}-homeassistant = "1"

ALLOW_EMPTY:${PN}-homeassistant-alerts = "1"

ALLOW_EMPTY:${PN}-homeassistant-connect-zbt2 = "1"

ALLOW_EMPTY:${PN}-homeassistant-green = "1"

ALLOW_EMPTY:${PN}-homeassistant-sky-connect = "1"

ALLOW_EMPTY:${PN}-homeassistant-yellow = "1"

ALLOW_EMPTY:${PN}-homekit = "1"
RDEPENDS:${PN}-homekit = "\
    python3-hap-python (>=5.0.0) \
    python3-fnv-hash-fast (>=1.5.0) \
    python3-pyqrcode (>=1.2.1) \
    python3-base36 (>=0.1.1) \
"

ALLOW_EMPTY:${PN}-http = "1"

ALLOW_EMPTY:${PN}-hue = "1"
RDEPENDS:${PN}-hue = "\
    python3-aiohue (>=4.7.5) \
"

ALLOW_EMPTY:${PN}-humidifier = "1"

ALLOW_EMPTY:${PN}-hurrican-shutters-wholesale = "1"

ALLOW_EMPTY:${PN}-husqvarna-automower-ble = "1"
RDEPENDS:${PN}-husqvarna-automower-ble = "\
    python3-automower-ble (>=0.2.7) \
    python3-gardena-bluetooth (>=1.6.0) \
"

ALLOW_EMPTY:${PN}-ibeacon = "1"
RDEPENDS:${PN}-ibeacon = "\
    python3-ibeacon-ble (>=1.2.0) \
"

ALLOW_EMPTY:${PN}-image = "1"

ALLOW_EMPTY:${PN}-image-processing = "1"

ALLOW_EMPTY:${PN}-image-upload = "1"
RDEPENDS:${PN}-image-upload = "\
    python3-pillow (>=11.3.0) \
"

ALLOW_EMPTY:${PN}-indianamichiganpower = "1"

ALLOW_EMPTY:${PN}-input-boolean = "1"

ALLOW_EMPTY:${PN}-input-button = "1"

ALLOW_EMPTY:${PN}-input-datetime = "1"

ALLOW_EMPTY:${PN}-input-number = "1"

ALLOW_EMPTY:${PN}-input-select = "1"

ALLOW_EMPTY:${PN}-input-text = "1"

ALLOW_EMPTY:${PN}-inspired-shades = "1"

ALLOW_EMPTY:${PN}-integration = "1"

ALLOW_EMPTY:${PN}-intent = "1"

ALLOW_EMPTY:${PN}-intent-script = "1"

ALLOW_EMPTY:${PN}-ios = "1"

ALLOW_EMPTY:${PN}-ipp = "1"
RDEPENDS:${PN}-ipp = "\
    python3-pyipp (>=0.17.0) \
"

ALLOW_EMPTY:${PN}-isal = "1"
RDEPENDS:${PN}-isal = "\
    python3-isal (>=1.7.1) \
"

ALLOW_EMPTY:${PN}-ismartwindow = "1"

ALLOW_EMPTY:${PN}-itunes = "1"

ALLOW_EMPTY:${PN}-juicenet = "1"

ALLOW_EMPTY:${PN}-kaiser-nienhaus = "1"

ALLOW_EMPTY:${PN}-kankun = "1"

ALLOW_EMPTY:${PN}-kentuckypower = "1"

ALLOW_EMPTY:${PN}-keyboard-remote = "1"
RDEPENDS:${PN}-keyboard-remote = "\
    python3-evdev (>=1.6.1) \
    python3-asyncinotify (>=4.2.0) \
"

ALLOW_EMPTY:${PN}-kitchen-sink = "1"

ALLOW_EMPTY:${PN}-konnected-esphome = "1"

ALLOW_EMPTY:${PN}-krispol = "1"

ALLOW_EMPTY:${PN}-kwb = "1"
RDEPENDS:${PN}-kwb = "\
    python3-pykwb (>=0.0.8) \
"

ALLOW_EMPTY:${PN}-labs = "1"

ALLOW_EMPTY:${PN}-lannouncer = "1"

ALLOW_EMPTY:${PN}-lawn-mower = "1"

ALLOW_EMPTY:${PN}-legrand = "1"

ALLOW_EMPTY:${PN}-letpot = "1"
RDEPENDS:${PN}-letpot = "\
    python3-letpot (>=0.6.2) \
"

ALLOW_EMPTY:${PN}-levoit = "1"

ALLOW_EMPTY:${PN}-life360 = "1"

ALLOW_EMPTY:${PN}-lifx-cloud = "1"

ALLOW_EMPTY:${PN}-light = "1"

ALLOW_EMPTY:${PN}-linak = "1"

ALLOW_EMPTY:${PN}-linkedgo = "1"

ALLOW_EMPTY:${PN}-linksys-smart = "1"

ALLOW_EMPTY:${PN}-linx = "1"

ALLOW_EMPTY:${PN}-llamalab-automate = "1"

ALLOW_EMPTY:${PN}-local-calendar = "1"
RDEPENDS:${PN}-local-calendar = "\
    python3-ical (>=11.0.0) \
"

ALLOW_EMPTY:${PN}-local-file = "1"

ALLOW_EMPTY:${PN}-local-ip = "1"

ALLOW_EMPTY:${PN}-local-todo = "1"
RDEPENDS:${PN}-local-todo = "\
    python3-ical (>=11.0.0) \
"

ALLOW_EMPTY:${PN}-locative = "1"

ALLOW_EMPTY:${PN}-lock = "1"

ALLOW_EMPTY:${PN}-logbook = "1"

ALLOW_EMPTY:${PN}-logentries = "1"

ALLOW_EMPTY:${PN}-logger = "1"

ALLOW_EMPTY:${PN}-london-air = "1"

ALLOW_EMPTY:${PN}-lovelace = "1"

ALLOW_EMPTY:${PN}-luftdaten = "1"
RDEPENDS:${PN}-luftdaten = "\
    python3-luftdaten (>=0.7.4) \
"

ALLOW_EMPTY:${PN}-luxaflex = "1"

ALLOW_EMPTY:${PN}-madeco = "1"

ALLOW_EMPTY:${PN}-manual = "1"

ALLOW_EMPTY:${PN}-manual-mqtt = "1"

ALLOW_EMPTY:${PN}-marantz = "1"

ALLOW_EMPTY:${PN}-martec = "1"

ALLOW_EMPTY:${PN}-matter = "1"
RDEPENDS:${PN}-matter = "\
    python3-python-matter-server (>=8.1.0) \
"

ALLOW_EMPTY:${PN}-maytag = "1"

ALLOW_EMPTY:${PN}-mazda = "1"

ALLOW_EMPTY:${PN}-mcp = "1"
RDEPENDS:${PN}-mcp = "\
    python3-mcp (>=1.5.0) \
"

ALLOW_EMPTY:${PN}-mcp-server = "1"
RDEPENDS:${PN}-mcp-server = "\
    python3-mcp (>=1.26.0) \
    python3-aiohttp-sse (>=2.2.0) \
    python3-anyio (>=4.10.0) \
"

ALLOW_EMPTY:${PN}-media-player = "1"

ALLOW_EMPTY:${PN}-media-source = "1"

ALLOW_EMPTY:${PN}-meraki = "1"

ALLOW_EMPTY:${PN}-met = "1"
RDEPENDS:${PN}-met = "\
    python3-pymetno (>=0.13.0) \
"

ALLOW_EMPTY:${PN}-microsoft-face = "1"

ALLOW_EMPTY:${PN}-microsoft-face-detect = "1"

ALLOW_EMPTY:${PN}-microsoft-face-identify = "1"

ALLOW_EMPTY:${PN}-mijndomein-energie = "1"

ALLOW_EMPTY:${PN}-min-max = "1"

ALLOW_EMPTY:${PN}-mini-connected = "1"

ALLOW_EMPTY:${PN}-mjpeg = "1"

ALLOW_EMPTY:${PN}-mobile-app = "1"
RDEPENDS:${PN}-mobile-app = "\
    python3-pynacl (>=1.5.0) \
"

ALLOW_EMPTY:${PN}-modbus = "1"
RDEPENDS:${PN}-modbus = "\
    python3-pymodbus (>=3.11.1) \
"

ALLOW_EMPTY:${PN}-mold-indicator = "1"

ALLOW_EMPTY:${PN}-monessen = "1"

ALLOW_EMPTY:${PN}-moon = "1"

ALLOW_EMPTY:${PN}-mqtt = "1"
RDEPENDS:${PN}-mqtt = "\
    python3-paho-mqtt (>=2.1.0) \
"

ALLOW_EMPTY:${PN}-mqtt-eventstream = "1"

ALLOW_EMPTY:${PN}-mqtt-json = "1"

ALLOW_EMPTY:${PN}-mqtt-room = "1"

ALLOW_EMPTY:${PN}-mqtt-statestream = "1"

ALLOW_EMPTY:${PN}-my = "1"

ALLOW_EMPTY:${PN}-myq = "1"

ALLOW_EMPTY:${PN}-namecheapdns = "1"
RDEPENDS:${PN}-namecheapdns = "\
    python3-defusedxml (>=0.7.1) \
"

ALLOW_EMPTY:${PN}-national-grid-us = "1"

ALLOW_EMPTY:${PN}-neff = "1"

ALLOW_EMPTY:${PN}-neo = "1"

ALLOW_EMPTY:${PN}-network = "1"
RDEPENDS:${PN}-network = "\
    python3-ifaddr (>=0.2.0) \
"

ALLOW_EMPTY:${PN}-nexity = "1"

ALLOW_EMPTY:${PN}-nmap-tracker = "1"
RDEPENDS:${PN}-nmap-tracker = "\
    python3-aiooui (>=0.1.9) \
    python3-getmac (>=0.9.5) \
    python3-netmap (>=0.7.0.2) \
"

ALLOW_EMPTY:${PN}-no-ip = "1"

ALLOW_EMPTY:${PN}-norway-air = "1"
RDEPENDS:${PN}-norway-air = "\
    python3-pymetno (>=0.13.0) \
"

ALLOW_EMPTY:${PN}-notify = "1"

ALLOW_EMPTY:${PN}-number = "1"

ALLOW_EMPTY:${PN}-nutrichef = "1"

ALLOW_EMPTY:${PN}-octoprint = "1"
RDEPENDS:${PN}-octoprint = "\
    python3-pyoctoprintapi (>=0.1.14) \
"

ALLOW_EMPTY:${PN}-ogemray = "1"

ALLOW_EMPTY:${PN}-ohmconnect = "1"
RDEPENDS:${PN}-ohmconnect = "\
    python3-defusedxml (>=0.7.1) \
"

ALLOW_EMPTY:${PN}-onboarding = "1"

ALLOW_EMPTY:${PN}-oncue = "1"

ALLOW_EMPTY:${PN}-openai-conversation = "1"
RDEPENDS:${PN}-openai-conversation = "\
    python3-openai (>=2.21.0) \
"

ALLOW_EMPTY:${PN}-openalpr-cloud = "1"

ALLOW_EMPTY:${PN}-openhardwaremonitor = "1"

ALLOW_EMPTY:${PN}-oru-opower = "1"

ALLOW_EMPTY:${PN}-otp = "1"
RDEPENDS:${PN}-otp = "\
    python3-pyotp (>=2.8.0) \
"

ALLOW_EMPTY:${PN}-owntracks = "1"
RDEPENDS:${PN}-owntracks = "\
    python3-pynacl (>=1.5.0) \
"

ALLOW_EMPTY:${PN}-panel-custom = "1"

ALLOW_EMPTY:${PN}-pcs-lighting = "1"

ALLOW_EMPTY:${PN}-peblar = "1"
RDEPENDS:${PN}-peblar = "\
    python3-peblar (>=0.4.0) \
"

ALLOW_EMPTY:${PN}-peco = "1"
RDEPENDS:${PN}-peco = "\
    python3-peco (>=0.1.2) \
"

ALLOW_EMPTY:${PN}-peco-opower = "1"

ALLOW_EMPTY:${PN}-pepco = "1"

ALLOW_EMPTY:${PN}-persistent-notification = "1"

ALLOW_EMPTY:${PN}-person = "1"

ALLOW_EMPTY:${PN}-pge = "1"

ALLOW_EMPTY:${PN}-picotts = "1"

ALLOW_EMPTY:${PN}-pinecil = "1"

ALLOW_EMPTY:${PN}-ping = "1"
RDEPENDS:${PN}-ping = "\
    python3-icmplib (>=3.0) \
"

ALLOW_EMPTY:${PN}-pioneer = "1"

ALLOW_EMPTY:${PN}-piper = "1"

ALLOW_EMPTY:${PN}-pitsos = "1"

ALLOW_EMPTY:${PN}-plant = "1"

ALLOW_EMPTY:${PN}-plum-lightpad = "1"

ALLOW_EMPTY:${PN}-portlandgeneral = "1"

ALLOW_EMPTY:${PN}-private-ble-device = "1"
RDEPENDS:${PN}-private-ble-device = "\
    python3-bluetooth-data-tools (>=1.28.2) \
"

ALLOW_EMPTY:${PN}-profilo = "1"

ALLOW_EMPTY:${PN}-proximity = "1"

ALLOW_EMPTY:${PN}-proxy = "1"
RDEPENDS:${PN}-proxy = "\
    python3-pillow (>=11.3.0) \
"

ALLOW_EMPTY:${PN}-pse = "1"

ALLOW_EMPTY:${PN}-psoklahoma = "1"

ALLOW_EMPTY:${PN}-pulseaudio-loopback = "1"
RDEPENDS:${PN}-pulseaudio-loopback = "\
    python3-pulsectl (>=23.5.2) \
"

ALLOW_EMPTY:${PN}-push = "1"

ALLOW_EMPTY:${PN}-pushsafer = "1"

ALLOW_EMPTY:${PN}-quadrafire = "1"

ALLOW_EMPTY:${PN}-qwikswitch = "1"
RDEPENDS:${PN}-qwikswitch = "\
    python3-pyqwikswitch (>=0.93) \
"

ALLOW_EMPTY:${PN}-radio-browser = "1"
RDEPENDS:${PN}-radio-browser = "\
    python3-radios (>=0.3.2) \
    python3-pycountry (>=24.6.1) \
"

ALLOW_EMPTY:${PN}-random = "1"

ALLOW_EMPTY:${PN}-raspberry-pi = "1"

ALLOW_EMPTY:${PN}-raven-rock-mfg = "1"

ALLOW_EMPTY:${PN}-recorder = "1"
RDEPENDS:${PN}-recorder = "\
    python3-sqlite3 \
    python3-fnv-hash-fast (>=1.5.0) \
    python3-sqlalchemy (>=2.0.41) \
    python3-psutil-home-assistant (>=0.0.1) \
"

ALLOW_EMPTY:${PN}-recovery-mode = "1"

ALLOW_EMPTY:${PN}-remote = "1"

ALLOW_EMPTY:${PN}-remote-calendar = "1"
RDEPENDS:${PN}-remote-calendar = "\
    python3-ical (>=13.2.0) \
"

ALLOW_EMPTY:${PN}-repairs = "1"

ALLOW_EMPTY:${PN}-rest = "1"
RDEPENDS:${PN}-rest = "\
    python3-jsonpath (>=0.82.2) \
    python3-xmltodict (>=1.0.2) \
"

ALLOW_EMPTY:${PN}-rest-command = "1"

ALLOW_EMPTY:${PN}-rexel = "1"

ALLOW_EMPTY:${PN}-rhasspy = "1"

ALLOW_EMPTY:${PN}-route53 = "1"
RDEPENDS:${PN}-route53 = "\
    python3-boto3 (>=1.37.1) \
"

ALLOW_EMPTY:${PN}-rss-feed-template = "1"

ALLOW_EMPTY:${PN}-rtorrent = "1"

ALLOW_EMPTY:${PN}-ruuvi-gateway = "1"
RDEPENDS:${PN}-ruuvi-gateway = "\
    python3-aioruuvigateway (>=0.1.0) \
"

ALLOW_EMPTY:${PN}-samsam = "1"

ALLOW_EMPTY:${PN}-scene = "1"

ALLOW_EMPTY:${PN}-schedule = "1"

ALLOW_EMPTY:${PN}-scl = "1"

ALLOW_EMPTY:${PN}-scrape = "1"
RDEPENDS:${PN}-scrape = "\
    python3-beautifulsoup4 (>=4.13.3) \
    python3-lxml (>=6.0.1) \
"

ALLOW_EMPTY:${PN}-screenaway = "1"

ALLOW_EMPTY:${PN}-script = "1"

ALLOW_EMPTY:${PN}-search = "1"

ALLOW_EMPTY:${PN}-select = "1"

ALLOW_EMPTY:${PN}-sense = "1"
RDEPENDS:${PN}-sense = "\
    python3-sense-energy (>=0.13.8) \
"

ALLOW_EMPTY:${PN}-sensor = "1"

ALLOW_EMPTY:${PN}-sensorblue = "1"

ALLOW_EMPTY:${PN}-sentry = "1"
RDEPENDS:${PN}-sentry = "\
    python3-sentry-sdk (>=1.45.1) \
"

ALLOW_EMPTY:${PN}-serial = "1"
RDEPENDS:${PN}-serial = "\
    python3-pyserial-asyncio-fast (>=0.16) \
"

ALLOW_EMPTY:${PN}-seven-segments = "1"
RDEPENDS:${PN}-seven-segments = "\
    python3-pillow (>=11.3.0) \
"

ALLOW_EMPTY:${PN}-sftp-storage = "1"
RDEPENDS:${PN}-sftp-storage = "\
    python3-asyncssh (>=2.21.0) \
"

ALLOW_EMPTY:${PN}-shell-command = "1"

ALLOW_EMPTY:${PN}-shelly = "1"
RDEPENDS:${PN}-shelly = "\
    python3-aioshelly (>=13.8.0) \
"

ALLOW_EMPTY:${PN}-shopping-list = "1"

ALLOW_EMPTY:${PN}-siemens = "1"

ALLOW_EMPTY:${PN}-sigfox = "1"

ALLOW_EMPTY:${PN}-simplisafe = "1"
RDEPENDS:${PN}-simplisafe = "\
    python3-simplisafe-python (>=2024.01.0) \
"

ALLOW_EMPTY:${PN}-simply-automated = "1"

ALLOW_EMPTY:${PN}-simu = "1"

ALLOW_EMPTY:${PN}-siren = "1"

ALLOW_EMPTY:${PN}-sleep-as-android = "1"

ALLOW_EMPTY:${PN}-smart-blinds = "1"

ALLOW_EMPTY:${PN}-smart-home = "1"

ALLOW_EMPTY:${PN}-smart-rollos = "1"

ALLOW_EMPTY:${PN}-smarther = "1"

ALLOW_EMPTY:${PN}-smartthings = "1"
RDEPENDS:${PN}-smartthings = "\
    python3-pysmartthings (>=3.2.5) \
"

ALLOW_EMPTY:${PN}-smtp = "1"

ALLOW_EMPTY:${PN}-smud = "1"

ALLOW_EMPTY:${PN}-snmp = "1"
RDEPENDS:${PN}-snmp = "\
    python3-pysnmp (>=7.1.22) \
"

ALLOW_EMPTY:${PN}-somfy = "1"

ALLOW_EMPTY:${PN}-sony-projector = "1"
RDEPENDS:${PN}-sony-projector = "\
    python3-pysdcp (>=1) \
"

ALLOW_EMPTY:${PN}-spaceapi = "1"

ALLOW_EMPTY:${PN}-speedtestdotnet = "1"
RDEPENDS:${PN}-speedtestdotnet = "\
    python3-speedtest-cli (>=2.1.3) \
"

ALLOW_EMPTY:${PN}-spider = "1"

ALLOW_EMPTY:${PN}-spotify = "1"
RDEPENDS:${PN}-spotify = "\
    python3-spotifyaio (>=1.0.0) \
"

ALLOW_EMPTY:${PN}-sql = "1"
RDEPENDS:${PN}-sql = "\
    python3-sqlalchemy (>=2.0.41) \
    python3-sqlparse (>=0.5.0) \
"

ALLOW_EMPTY:${PN}-ssdp = "1"
RDEPENDS:${PN}-ssdp = "\
    python3-async-upnp-client (>=0.45.0) \
"

ALLOW_EMPTY:${PN}-startca = "1"
RDEPENDS:${PN}-startca = "\
    python3-xmltodict (>=0.13.0) \
"

ALLOW_EMPTY:${PN}-statistics = "1"

ALLOW_EMPTY:${PN}-steam-online = "1"
RDEPENDS:${PN}-steam-online = "\
    python3-steamodd (>=4.21) \
"

ALLOW_EMPTY:${PN}-stream = "1"
RDEPENDS:${PN}-stream = "\
    python3-pyturbojpeg (>=1.8.0) \
    python3-av (>=13.1.0) \
    python3-numpy (>=2.3.2) \
"

ALLOW_EMPTY:${PN}-stt = "1"

ALLOW_EMPTY:${PN}-sun = "1"

ALLOW_EMPTY:${PN}-sunweg = "1"

ALLOW_EMPTY:${PN}-supervisord = "1"

ALLOW_EMPTY:${PN}-swepco = "1"

ALLOW_EMPTY:${PN}-swisscom = "1"

ALLOW_EMPTY:${PN}-switch = "1"

ALLOW_EMPTY:${PN}-switch-as-x = "1"

ALLOW_EMPTY:${PN}-switchbot = "1"
RDEPENDS:${PN}-switchbot = "\
    python3-pyswitchbot (>=0.69.0) \
"

ALLOW_EMPTY:${PN}-symfonisk = "1"

ALLOW_EMPTY:${PN}-synology-chat = "1"

ALLOW_EMPTY:${PN}-syslog = "1"

ALLOW_EMPTY:${PN}-system-health = "1"

ALLOW_EMPTY:${PN}-system-log = "1"

ALLOW_EMPTY:${PN}-systemmonitor = "1"
RDEPENDS:${PN}-systemmonitor = "\
    python3-psutil (>=7.0.0) \
    python3-psutil-home-assistant (>=0.0.1) \
"

ALLOW_EMPTY:${PN}-tag = "1"

ALLOW_EMPTY:${PN}-tcp = "1"

ALLOW_EMPTY:${PN}-ted5000 = "1"
RDEPENDS:${PN}-ted5000 = "\
    python3-xmltodict (>=0.13.0) \
"

ALLOW_EMPTY:${PN}-telegram = "1"

ALLOW_EMPTY:${PN}-telnet = "1"

ALLOW_EMPTY:${PN}-template = "1"

ALLOW_EMPTY:${PN}-text = "1"

ALLOW_EMPTY:${PN}-thermador = "1"

ALLOW_EMPTY:${PN}-thermoplus = "1"

ALLOW_EMPTY:${PN}-thomson = "1"

ALLOW_EMPTY:${PN}-threshold = "1"

ALLOW_EMPTY:${PN}-tibber = "1"
RDEPENDS:${PN}-tibber = "\
    python3-pytibber (>=0.31.6) \
"

ALLOW_EMPTY:${PN}-time = "1"

ALLOW_EMPTY:${PN}-time-date = "1"

ALLOW_EMPTY:${PN}-timer = "1"

ALLOW_EMPTY:${PN}-tod = "1"

ALLOW_EMPTY:${PN}-todo = "1"

ALLOW_EMPTY:${PN}-tomato = "1"

ALLOW_EMPTY:${PN}-torque = "1"

ALLOW_EMPTY:${PN}-tplink-tapo = "1"

ALLOW_EMPTY:${PN}-trace = "1"

ALLOW_EMPTY:${PN}-trafikverket-camera = "1"
RDEPENDS:${PN}-trafikverket-camera = "\
    python3-pytrafikverket (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-trafikverket-ferry = "1"
RDEPENDS:${PN}-trafikverket-ferry = "\
    python3-pytrafikverket (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-trafikverket-train = "1"
RDEPENDS:${PN}-trafikverket-train = "\
    python3-pytrafikverket (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-trafikverket-weatherstation = "1"
RDEPENDS:${PN}-trafikverket-weatherstation = "\
    python3-pytrafikverket (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-trend = "1"
RDEPENDS:${PN}-trend = "\
    python3-numpy (>=2.3.2) \
"

ALLOW_EMPTY:${PN}-tts = "1"
RDEPENDS:${PN}-tts = "\
    python3-mutagen (>=1.47.0) \
"

ALLOW_EMPTY:${PN}-twilio-call = "1"

ALLOW_EMPTY:${PN}-twilio-sms = "1"

ALLOW_EMPTY:${PN}-ubiwizz = "1"

ALLOW_EMPTY:${PN}-ublockout = "1"

ALLOW_EMPTY:${PN}-uk-transport = "1"

ALLOW_EMPTY:${PN}-ultraloq = "1"

ALLOW_EMPTY:${PN}-universal = "1"

ALLOW_EMPTY:${PN}-update = "1"

ALLOW_EMPTY:${PN}-upnp = "1"
RDEPENDS:${PN}-upnp = "\
    python3-async-upnp-client (>=0.45.0) \
    python3-getmac (>=0.9.5) \
"

ALLOW_EMPTY:${PN}-uprise-smart-shades = "1"

ALLOW_EMPTY:${PN}-uptime = "1"

ALLOW_EMPTY:${PN}-usage-prediction = "1"

ALLOW_EMPTY:${PN}-usb = "1"
RDEPENDS:${PN}-usb = "\
    python3-pyserial (>=3.5) \
    python3-aiousbwatcher (>=1.1.1) \
"

ALLOW_EMPTY:${PN}-utility-meter = "1"
RDEPENDS:${PN}-utility-meter = "\
    python3-cronsim (>=2.6) \
"

ALLOW_EMPTY:${PN}-vacuum = "1"

ALLOW_EMPTY:${PN}-vagner-pool = "1"

ALLOW_EMPTY:${PN}-valve = "1"

ALLOW_EMPTY:${PN}-vermont-castings = "1"

ALLOW_EMPTY:${PN}-vlc = "1"
RDEPENDS:${PN}-vlc = "\
    python3-python-vlc (>=3.0.18122) \
"

ALLOW_EMPTY:${PN}-voicerss = "1"

ALLOW_EMPTY:${PN}-volvooncall = "1"

ALLOW_EMPTY:${PN}-w800rf32 = "1"
RDEPENDS:${PN}-w800rf32 = "\
    python3-pyw800rf32 (>= 0.4) \
"

ALLOW_EMPTY:${PN}-wake-word = "1"

ALLOW_EMPTY:${PN}-wakeonlan = "1"
RDEPENDS:${PN}-wakeonlan = "\
    python3-wakeonlan (>=3.1.0) \
"

ALLOW_EMPTY:${PN}-water-heater = "1"

ALLOW_EMPTY:${PN}-weather = "1"

ALLOW_EMPTY:${PN}-web-rtc = "1"

ALLOW_EMPTY:${PN}-webhook = "1"

ALLOW_EMPTY:${PN}-websocket-api = "1"

ALLOW_EMPTY:${PN}-whisper = "1"

ALLOW_EMPTY:${PN}-wirelesstag = "1"
RDEPENDS:${PN}-wirelesstag = "\
    python3-wirelesstagpy (>=0.8.1) \
"

ALLOW_EMPTY:${PN}-worldclock = "1"

ALLOW_EMPTY:${PN}-worldtidesinfo = "1"

ALLOW_EMPTY:${PN}-worxlandroid = "1"

ALLOW_EMPTY:${PN}-x10 = "1"

ALLOW_EMPTY:${PN}-xiaomi = "1"

ALLOW_EMPTY:${PN}-yale = "1"
RDEPENDS:${PN}-yale = "\
    python3-yalexs (>=9.2.0) \
    python3-yalexs-ble (>=3.2.7) \
"
ALLOW_EMPTY:${PN}-yalexs-ble = "1"
RDEPENDS:${PN}-yalexs-ble = "\
    python3-yalexs-ble (>=3.2.7) \
"

ALLOW_EMPTY:${PN}-yandextts = "1"

ALLOW_EMPTY:${PN}-zabbix = "1"
RDEPENDS:${PN}-zabbix = "\
    python3-zabbix-utils (>=2.0.2) \
"

ALLOW_EMPTY:${PN}-zbox-hub = "1"

ALLOW_EMPTY:${PN}-zengge = "1"

ALLOW_EMPTY:${PN}-zeroconf = "1"
RDEPENDS:${PN}-zeroconf = "\
    python3-zeroconf (>=0.147.0) \
"

ALLOW_EMPTY:${PN}-zestimate = "1"
RDEPENDS:${PN}-zestimate = "\
    python3-xmltodict (>=0.13.0) \
"

ALLOW_EMPTY:${PN}-zha = "1"
RDEPENDS:${PN}-zha = "\
    python3-zha (>=0.0.70) \
"

ALLOW_EMPTY:${PN}-zodiac = "1"

ALLOW_EMPTY:${PN}-zondergas = "1"

ALLOW_EMPTY:${PN}-zone = "1"

ALLOW_EMPTY:${PN}-zoneminder = "1"
RDEPENDS:${PN}-zoneminder = "\
    python3-zm-py (>=0.5.4) \
"

ALLOW_EMPTY:${PN}-zwave-js = "1"
RDEPENDS:${PN}-zwave-js = "\
    python3-pyserial (>=3.5) \
    python3-zwave-js-server-python (>=0.67.1) \
"

ALLOW_EMPTY:${PN}-zwave-me = "1"
RDEPENDS:${PN}-zwave-me = "\
    python3-url-normalize (>=2.2.1) \
    python3-zwave-me-ws (>=0.4.3) \
"

