#!/bin/sh

# test_get_system_info_supervisor_not_loaded is skipped due to the fact that this is an unsupported way of running HA.
# The following tests seem to fail and needs investigation

# pytest -n auto --automake \
#   --ignore=tests/components/ \
#   -k "not test_get_system_info_supervisor_not_loaded \
#   and not test_merge \
#   and not test_evict_faked_translations \
#   and not test_track_time_interval_name \
#   and not test_config_platform_valid \
#   "
