#!/bin/sh

# test_get_system_info_supervisor_not_loaded is skipped due to the fact that this is an unsupported way of running HA.
# The following tests seem to fail and needs investigation

pytest -n auto --force-sugar --automake --retries 2 --retry-delay 5\
  --ignore=tests/components/ \
  -k "not test_get_system_info_supervisor_not_loaded \
  and not test_merge \
  and not test_track_time_interval_name \
  and not test_config_platform_valid \
  "