#!/bin/sh

pytest --automake \
  --ignore=tests/auth/ \
  --ignore=tests/components/ \
  --ignore=tests/hassfest/ \
  --ignore=tests/helpers/ \
  --ignore=tests/non_packaged_scripts/ \
  --ignore=tests/pylint/ \
  --ignore=tests/resources/ \
  --ignore=tests/script/ \
  --ignore=tests/scripts/ \
  --ignore=tests/snapshots/ \
  --ignore=tests/test_util/ \
  --ignore=tests/testing_config/ \
  --ignore=tests/test_config.py \
  --ignore=tests/util/ \
  --ignore=tests/test_core.py 