SUMMARY = "A full featured image capable of running Home Assistant and has all available components installed"

IMAGE_INSTALL = "\
    packagegroup-core-boot \
    ${CORE_IMAGE_EXTRA_INSTALL} \
    python3-homeassistant \
    \
    python3-homeassistant-acaia \
    python3-homeassistant-accuweather \
    python3-homeassistant-acer-projector \
    python3-homeassistant-acmeda \
    python3-homeassistant-adax \
    python3-homeassistant-adguard \
    python3-homeassistant-advantage-air \
    python3-homeassistant-aemet \
    python3-homeassistant-aftership \
    python3-homeassistant-agent-dvr \
    python3-homeassistant-airgradient \
    python3-homeassistant-airly \
    python3-homeassistant-airnow \
    python3-homeassistant-airos \
    python3-homeassistant-airq \
    python3-homeassistant-airthings \
    python3-homeassistant-airthings-ble \
    python3-homeassistant-airtouch4 \
    python3-homeassistant-airtouch5 \
    python3-homeassistant-airvisual \
    python3-homeassistant-airvisual-pro \
    python3-homeassistant-airzone \
    python3-homeassistant-airzone-cloud \
    python3-homeassistant-aladdin-connect \
    python3-homeassistant-alarmdecoder \
    python3-homeassistant-alpha-vantage \
    python3-homeassistant-altruist \
    python3-homeassistant-amazon-polly \
    python3-homeassistant-amberelectric \
    python3-homeassistant-ambient-network \
    python3-homeassistant-ambient-station \
    python3-homeassistant-amcrest \
    python3-homeassistant-ampio \
    python3-homeassistant-analytics-insights \
    python3-homeassistant-android-ip-webcam \
    python3-homeassistant-androidtv \
    python3-homeassistant-androidtv-remote \
    python3-homeassistant-anel-pwrctrl \
    python3-homeassistant-anova \
    python3-homeassistant-anthemav \
    python3-homeassistant-anthropic \
    python3-homeassistant-aosmith \
    python3-homeassistant-apache-kafka \
    python3-homeassistant-apcupsd \
    python3-homeassistant-apple-tv \
    python3-homeassistant-aprilaire \
    python3-homeassistant-aprs \
    python3-homeassistant-apsystems \
    python3-homeassistant-aqualogic \
    python3-homeassistant-aquostv \
    python3-homeassistant-aranet \
    python3-homeassistant-arcam-fmj \
    python3-homeassistant-arris-tg2492lg \
    python3-homeassistant-aruba \
    python3-homeassistant-arve \
    python3-homeassistant-aseko-pool-live \
    python3-homeassistant-assist-pipeline \
    python3-homeassistant-asuswrt \
    python3-homeassistant-atag \
    python3-homeassistant-aten-pe \
    python3-homeassistant-atome \
    python3-homeassistant-august \
    python3-homeassistant-aurora-abb-powerone \
    python3-homeassistant-aussie-broadband \
    python3-homeassistant-autarco \
    python3-homeassistant-avea \
    python3-homeassistant-avion \
    python3-homeassistant-awair \
    python3-homeassistant-aws \
    python3-homeassistant-aws-s3 \
    python3-homeassistant-axis \
    python3-homeassistant-azure-data-explorer \
    python3-homeassistant-azure-devops \
    python3-homeassistant-azure-event-hub \
    python3-homeassistant-azure-service-bus \
    python3-homeassistant-azure-storage \
    python3-homeassistant-backup \
    python3-homeassistant-baf \
    python3-homeassistant-baidu \
    python3-homeassistant-balboa \
    python3-homeassistant-bang-olufsen \
    python3-homeassistant-bbox \
    python3-homeassistant-beewi-smartclim \
    python3-homeassistant-bitcoin \
    python3-homeassistant-bizkaibus \
    python3-homeassistant-blackbird \
    python3-homeassistant-blebox \
    python3-homeassistant-blink \
    python3-homeassistant-blinksticklight \
    python3-homeassistant-blockchain \
    python3-homeassistant-blue-current \
    python3-homeassistant-bluemaestro \
    python3-homeassistant-bluesound \
    python3-homeassistant-bluetooth \
    python3-homeassistant-bluetooth-tracker \
    python3-homeassistant-bmw-connected-drive \
    python3-homeassistant-bond \
    python3-homeassistant-bosch-alarm \
    python3-homeassistant-bosch-shc \
    python3-homeassistant-braviatv \
    python3-homeassistant-bring \
    python3-homeassistant-broadlink \
    python3-homeassistant-brother \
    python3-homeassistant-brottsplatskartan \
    python3-homeassistant-brunt \
    python3-homeassistant-bryant-evolution \
    python3-homeassistant-bsblan \
    python3-homeassistant-bt-home-hub-5 \
    python3-homeassistant-bt-smarthub \
    python3-homeassistant-bthome \
    python3-homeassistant-buienradar \
    python3-homeassistant-caldav \
    python3-homeassistant-cambridge-audio \
    python3-homeassistant-camera \
    python3-homeassistant-canary \
    python3-homeassistant-cast \
    python3-homeassistant-ccm15 \
    python3-homeassistant-chacon-dio \
    python3-homeassistant-channels \
    python3-homeassistant-cisco-ios \
    python3-homeassistant-cisco-mobility-express \
    python3-homeassistant-cisco-webex-teams \
    python3-homeassistant-clementine \
    python3-homeassistant-cloud \
    python3-homeassistant-cloudflare \
    python3-homeassistant-cmus \
    python3-homeassistant-co2signal \
    python3-homeassistant-coinbase \
    python3-homeassistant-color-extractor \
    python3-homeassistant-comelit \
    python3-homeassistant-comfoconnect \
    python3-homeassistant-command-line \
    python3-homeassistant-compensation \
    python3-homeassistant-concord232 \
    python3-homeassistant-control4 \
    python3-homeassistant-conversation \
    python3-homeassistant-cookidoo \
    python3-homeassistant-coolmaster \
    python3-homeassistant-cppm-tracker \
    python3-homeassistant-cpuspeed \
    python3-homeassistant-crownstone \
    python3-homeassistant-cups \
    python3-homeassistant-daikin \
    python3-homeassistant-danfoss-air \
    python3-homeassistant-datadog \
    python3-homeassistant-deako \
    python3-homeassistant-debugpy \
    python3-homeassistant-deconz \
    python3-homeassistant-decora \
    python3-homeassistant-decora-wifi \
    python3-homeassistant-delijn \
    python3-homeassistant-deluge \
    python3-homeassistant-denonavr \
    python3-homeassistant-devialet \
    python3-homeassistant-devolo-home-control \
    python3-homeassistant-devolo-home-network \
    python3-homeassistant-dexcom \
    python3-homeassistant-dhcp \
    python3-homeassistant-digital-ocean \
    python3-homeassistant-directv \
    python3-homeassistant-discogs \
    python3-homeassistant-discord \
    python3-homeassistant-discovergy \
    python3-homeassistant-dlib-face-detect \
    python3-homeassistant-dlib-face-identify \
    python3-homeassistant-dlink \
    python3-homeassistant-dlna-dmr \
    python3-homeassistant-dlna-dms \
    python3-homeassistant-dnsip \
    python3-homeassistant-dominos \
    python3-homeassistant-doods \
    python3-homeassistant-doorbird \
    python3-homeassistant-dormakaba-dkey \
    python3-homeassistant-dovado \
    python3-homeassistant-dremel-3d-printer \
    python3-homeassistant-drop-connect \
    python3-homeassistant-dsmr \
    python3-homeassistant-duke-energy \
    python3-homeassistant-dunehd \
    python3-homeassistant-duotecno \
    python3-homeassistant-dwd-weather-warnings \
    python3-homeassistant-dynalite \
    python3-homeassistant-eafm \
    python3-homeassistant-easyenergy \
    python3-homeassistant-ebox \
    python3-homeassistant-ebusd \
    python3-homeassistant-ecoal-boiler \
    python3-homeassistant-ecobee \
    python3-homeassistant-ecoforest \
    python3-homeassistant-econet \
    python3-homeassistant-ecovacs \
    python3-homeassistant-ecowitt \
    python3-homeassistant-eddystone-temperature \
    python3-homeassistant-edimax \
    python3-homeassistant-edl21 \
    python3-homeassistant-efergy \
    python3-homeassistant-egardia \
    python3-homeassistant-eheimdigital \
    python3-homeassistant-electrasmart \
    python3-homeassistant-electric-kiwi \
    python3-homeassistant-elevenlabs \
    python3-homeassistant-elgato \
    python3-homeassistant-eliqonline \
    python3-homeassistant-elkm1 \
    python3-homeassistant-elmax \
    python3-homeassistant-elv \
    python3-homeassistant-elvia \
    python3-homeassistant-emby \
    python3-homeassistant-emoncms \
    python3-homeassistant-emoncms-history \
    python3-homeassistant-emonitor \
    python3-homeassistant-emulated-kasa \
    python3-homeassistant-emulated-roku \
    python3-homeassistant-energenie-power-sockets \
    python3-homeassistant-energyzero \
    python3-homeassistant-enigma2 \
    python3-homeassistant-enocean \
    python3-homeassistant-enphase-envoy \
    python3-homeassistant-entur-public-transport \
    python3-homeassistant-environment-canada \
    python3-homeassistant-envisalink \
    python3-homeassistant-ephember \
    python3-homeassistant-epic-games-store \
    python3-homeassistant-epion \
    python3-homeassistant-epson \
    python3-homeassistant-eq3btsmart \
    python3-homeassistant-escea \
    python3-homeassistant-esphome \
    python3-homeassistant-etherscan \
    python3-homeassistant-eufy \
    python3-homeassistant-eufylife-ble \
    python3-homeassistant-everlights \
    python3-homeassistant-evil-genius-labs \
    python3-homeassistant-evohome \
    python3-homeassistant-ezviz \
    python3-homeassistant-faa-delays \
    python3-homeassistant-familyhub \
    python3-homeassistant-fastdotcom \
    python3-homeassistant-feedreader \
    python3-homeassistant-ffmpeg \
    python3-homeassistant-fibaro \
    python3-homeassistant-fido \
    python3-homeassistant-file \
    python3-homeassistant-fints \
    python3-homeassistant-fireservicerota \
    python3-homeassistant-firmata \
    python3-homeassistant-fitbit \
    python3-homeassistant-fivem \
    python3-homeassistant-fixer \
    python3-homeassistant-fjaraskupan \
    python3-homeassistant-fleetgo \
    python3-homeassistant-flexit-bacnet \
    python3-homeassistant-flic \
    python3-homeassistant-flick-electric \
    python3-homeassistant-flipr \
    python3-homeassistant-flo \
    python3-homeassistant-flume \
    python3-homeassistant-flux-led \
    python3-homeassistant-folder-watcher \
    python3-homeassistant-foobot \
    python3-homeassistant-forecast-solar \
    python3-homeassistant-forked-daapd \
    python3-homeassistant-fortios \
    python3-homeassistant-foscam \
    python3-homeassistant-free-mobile \
    python3-homeassistant-freebox \
    python3-homeassistant-freedompro \
    python3-homeassistant-fritz \
    python3-homeassistant-fritzbox \
    python3-homeassistant-fritzbox-callmonitor \
    python3-homeassistant-fronius \
    python3-homeassistant-frontend \
    python3-homeassistant-frontier-silicon \
    python3-homeassistant-fujitsu-fglair \
    python3-homeassistant-fully-kiosk \
    python3-homeassistant-futurenow \
    python3-homeassistant-fyta \
    python3-homeassistant-generic \
    python3-homeassistant-github \
    python3-homeassistant-google-mail \
    python3-homeassistant-google-tasks \
    python3-homeassistant-google-translate \
    python3-homeassistant-hardware \
    python3-homeassistant-homekit \
    python3-homeassistant-hue \
    python3-homeassistant-image-upload \
    python3-homeassistant-ipp \
    python3-homeassistant-isal \
    python3-homeassistant-keyboard-remote \
    python3-homeassistant-kwb \
    python3-homeassistant-letpot \
    python3-homeassistant-local-calendar \
    python3-homeassistant-local-todo \
    python3-homeassistant-luftdaten \
    python3-homeassistant-matter \
    python3-homeassistant-mcp \
    python3-homeassistant-mcp-server \
    python3-homeassistant-met \
    python3-homeassistant-mobile-app \
    python3-homeassistant-modbus \
    python3-homeassistant-mqtt \
    python3-homeassistant-namecheapdns \
    python3-homeassistant-network \
    python3-homeassistant-nmap-tracker \
    python3-homeassistant-norway-air \
    python3-homeassistant-octoprint \
    python3-homeassistant-ohmconnect \
    python3-homeassistant-otp \
    python3-homeassistant-owntracks \
    python3-homeassistant-pandora \
    python3-homeassistant-peblar \
    python3-homeassistant-peco \
    python3-homeassistant-private-ble-device \
    python3-homeassistant-proxy \
    python3-homeassistant-pulseaudio-loopback \
    python3-homeassistant-qwikswitch \
    python3-homeassistant-radio-browser \
    python3-homeassistant-recorder \
    python3-homeassistant-route53 \
    python3-homeassistant-ruuvi-gateway \
    python3-homeassistant-scrape \
    python3-homeassistant-sentry \
    python3-homeassistant-seven-segments \
    python3-homeassistant-shelly \
    python3-homeassistant-simplisafe \
    python3-homeassistant-smartthings \
    python3-homeassistant-sony-projector \
    python3-homeassistant-speedtestdotnet \
    python3-homeassistant-sql \
    python3-homeassistant-ssdp \
    python3-homeassistant-startca \
    python3-homeassistant-steam-online \
    python3-homeassistant-stream \
    python3-homeassistant-switchbot \
    python3-homeassistant-systemmonitor \
    python3-homeassistant-ted5000 \
    python3-homeassistant-tibber \
    python3-homeassistant-trafikverket-camera \
    python3-homeassistant-trafikverket-ferry \
    python3-homeassistant-trafikverket-train \
    python3-homeassistant-trafikverket-weatherstation \
    python3-homeassistant-trend \
    python3-homeassistant-tts \
    python3-homeassistant-upnp \
    python3-homeassistant-usb \
    python3-homeassistant-utility-meter \
    python3-homeassistant-vlc \
    python3-homeassistant-zabbix \
    python3-homeassistant-zeroconf \
    python3-homeassistant-zestimate \
    python3-homeassistant-zha \
    python3-homeassistant-zoneminder \
    python3-homeassistant-zwave-js \
    python3-homeassistant-zwave-me \
    "

IMAGE_LINGUAS = ""

LICENSE = "MIT"

# 100 MiB of additional storage for config and runtime data
IMAGE_ROOTFS_EXTRA_SPACE = "102400"

inherit core-image
