SUMMARY = "A small python module for wake on lan."
HOMEPAGE = " https://github.com/remcohaszing/pywakeonlan"
LICENSE = "WTFPL"

#TODO: https://github.com/remcohaszing/pywakeonlan/pull/8
LIC_FILES_CHKSUM = "file://setup.py;md5=bf3bbd096afdfcfc98ef992c9c0bd436"

inherit pypi

SRC_URI[md5sum] = "91e0c97210875915af88ccb9103c866d"
SRC_URI[sha256sum] = "01faf75d0e166e419f01b16404109131b9d16b195cfaa2f1f57601780df3d3ea"
