SUMMARY = "A Philips Hue Python library"
HOMEPAGE = "https://github.com/studioimaginaire/phue"
LICENSE = "MIT"
#TODO: Use correct file once is fixed: https://github.com/studioimaginaire/phue/issues/92
#LIC_FILES_CHKSUM = "file://LICENSE;md5=d7dba1721bc8ce05d421f7279cb87971"
LIC_FILES_CHKSUM = "file://phue.py;md5=e10b96f83386aa6ab24044fc37603921;startline=4;endline=15"

inherit pypi

SRC_URI[md5sum] = "0c41a3cf27a5dbd86f63730096433b50"
SRC_URI[sha256sum] = "58b75475fdd3267b2708549f4185f4eee2658e72728dcc4b239439c7918a2cd7"