SUMMARY = "a Python module that provides an interface to the Yahoo! Weather RSS feed."
HOMEPAGE = "https://github.com/pvizeli/yahooweather"
LICENSE = "BSD-3-Clause"
#TODO: https://github.com/pvizeli/yahooweather/pull/4
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=4e0a1766bf1f5a3330f93a3cda9f4b63"

inherit pypi

PYPI_PACKAGE_EXT = "zip"

SRC_URI[md5sum] = "9cdac54c047aec906c30d10016d5c168"
SRC_URI[sha256sum] = "c531ade76d6f090784480ac468f0e27fc397a455b2f629bd519d7a3c21a19bf9"
