SUMMARY = "Python program and library to control Wi-Fi enabled iRobot Roomba vacuum cleaners"
HOMEPAGE = "https://github.com/pschmitt/roombapy"
LICENSE = "MIT"
#TODO: https://github.com/pschmitt/roombapy/pull/1
LIC_FILES_CHKSUM = "file://setup.py;md5=b21c9dedf56c1a1e78f874291ecaa7e5"

inherit pypi

SRC_URI[md5sum] = "c4cdc157d8c8e73af341f01e88f22ddd"
SRC_URI[sha256sum] = "9f638bb4ca2a76a323cf6cd39930c3918b9ebdd21203b1ded949d33ea954d3c8"
