SUMMARY = "Simple construction, analysis and modification of binary data."
HOMEPAGE = "https://github.com/scott-griffiths/bitstring"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=4680edc365ce7b05888336af92064330"

inherit pypi

PYPI_PACKAGE_EXT = "zip"

SRC_URI[md5sum] = "70689a282f66625d0c7c3579a13e66db"
SRC_URI[sha256sum] = "c163a86fcef377c314690051885d86b47419e3e1770990c212e16723c1c08faa"
