SUMMARY = "Simple python library to deal with URI Templates."
HOMEPAGE = "https://uritemplate.readthedocs.org"
LICENSE = "Apache-2.0 | BSD-3-Clause"
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=f2e14cc8f5f696fd9d47092e992265c1 \
    file://LICENSE.APACHE;md5=3b83ef96387f14655fc854ddc3c6bd57 \
    file://LICENSE.BSD;md5=d51d83fdbd6608d10a71666840ef5d15 \
"

inherit pypi

SRC_URI[md5sum] = "1ec31e0d8a2eec72357b2cef4bce5945"
SRC_URI[sha256sum] = "c02643cebe23fc8adb5e6becffe201185bf06c40bda5c0b4028a93f1527d011d"
