SUMMARY = "a Python module that provides an interface to the Yahoo! Weather RSS feed."
HOMEPAGE = "https://github.com/pvizeli/yahooweather"
LICENSE = "BSD-3-Clause"
#TODO: https://github.com/pvizeli/yahooweather/pull/4
LIC_FILES_CHKSUM = "file://PKG-INFO;md5=38bebb25979248e86e154b737d66becb"

inherit pypi

PYPI_PACKAGE_EXT = "tar.gz"

SRC_URI[md5sum] = "6c04bb5b8b89af62188720b10fdbe562"
SRC_URI[sha256sum] = "a51fe2f9cf4005968be58791e704865e8c54aa309fbd4a6d5f48a6e8526d1c04"
