SUMMARY = "A Philips Hue Python library"
HOMEPAGE = "https://github.com/studioimaginaire/phue"
LICENSE = "MIT"
#TODO: Use correct file once is fixed: https://github.com/studioimaginaire/phue/issues/92
#LIC_FILES_CHKSUM = "file://LICENSE;md5=d7dba1721bc8ce05d421f7279cb87971"
LIC_FILES_CHKSUM = "file://phue.py;md5=e10b96f83386aa6ab24044fc37603921;startline=4;endline=15"

inherit pypi

SRC_URI[md5sum] = "74d746ad85d3f5cf12adeec640a20dfd"
SRC_URI[sha256sum] = "14b8285ece83124a6b0f47b88a62b0a6c4f2901cd1d555e36c5927bfd7417515"