SUMMARY = "A thin Python Wrapper for the Dark Sky (formerly Forecast.io) weather API"
HOMEPAGE = "http://zeevgilovitz.com/python-forecast.io/"
LICENSE = "BSD-2-Clause"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=32c8803ff26092f3894bf31556fce677"

inherit pypi

PYPI_PACKAGE = "python-forecastio"

SRC_URI[md5sum] = "7024fb3a242a07423d6a0c66402305cd"
SRC_URI[sha256sum] = "144419d65e3b46961f38853f959a91f6e6cfa9e6d5b6f47aa9dc5e431471d454"
