SUMMARY = "Python client library for reading Server Sent Event streams."
HOMEPAGE = "https://github.com/btubbs/sseclient"
LICENSE = "MIT"

#TODO: https://github.com/btubbs/sseclient/pull/11
LIC_FILES_CHKSUM = "file://README.rst;md5=261df4ee81a6697c410e22fb829395f0"

inherit pypi

SRC_URI[md5sum] = "adbaeafe639aa81eb0d9aed3dc5b8c36"
SRC_URI[sha256sum] = "1b4c5119b9381cb6ddaf3236f3f7e1437a14e488d1ed61336873a839788481b0"
