SUMMARY = "A colored formatter for the python logging module"
HOMEPAGE = "https://github.com/borntyping/python-colorlog"
LICENSE = "MIT"
# TODO: Use real file once https://github.com/borntyping/python-colorlog/pull/46 if fixed
LIC_FILES_CHKSUM = "file://README.md;md5=e70a9e5286216e339891c9afebad3370"

inherit pypi

SRC_URI[md5sum] = "fffcb1520917874cc520267368bf6fab"
SRC_URI[sha256sum] = "229cd0794a19d8f33b2b4a4b70e1225b6c010af96c2dc8615279abbc1bb3929a"
