SUMMARY = "a Python module that provides an interface to the Yahoo! Weather RSS feed."
HOMEPAGE = "https://github.com/pvizeli/yahooweather"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://README.rst;md5=3cfaf283145919f5e077de6e72050b42"

inherit pypi

SRC_URI = "https://pypi.python.org/packages/40/f5/2810a8fbb65571e7d81fd7a1015c6da9e2a498f89aae31fb6cfb09480f87/yahooweather-0.8.zip"
SRC_URI[md5sum] = "9cdac54c047aec906c30d10016d5c168"
SRC_URI[sha256sum] = "c531ade76d6f090784480ac468f0e27fc397a455b2f629bd519d7a3c21a19bf9"


