SUMMARY = "A thin Python Wrapper for the Dark Sky (formerly Forecast.io) weather API"
HOMEPAGE = "http://zeevgilovitz.com/python-forecast.io/"
LICENSE = "BSD-2-Clause"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=32c8803ff26092f3894bf31556fce677"

inherit pypi

PYPI_PACKAGE = "python-forecastio"

SRC_URI[md5sum] = "551e369d65244617c8d1ca9b84e2951e"
SRC_URI[sha256sum] = "15cfcaea91b6eda0a67041e874c9a0c346e593f7dc5be8a513a5f581c63a1ed7"
