SUMMARY = "Convert Voluptuous schemas to dictionaries so they can be serialized."
HOMEPAGE = "http://github.com/balloob/voluptuous-serialize"
LICENSE = "Apache-2.0"
# FIXME: Github project has LICENSE file, but not the archive from
# https://pypi.org/project/voluptuous-serialize/
LIC_FILES_CHKSUM = "file://setup.py;md5=15ab6a49f2d6800300e05e99c4df9839"

inherit pypi

SRC_URI[md5sum] = "f8f297ed69152d82753d8e3ec4b7bf05"
SRC_URI[sha256sum] = "8b31660c7efdba0eb97ba65390b63cc62cc99ae3cd25d00e1873b183b38ef13d"
