SUMMARY = "A small python module for wake on lan."
HOMEPAGE = " https://github.com/remcohaszing/pywakeonlan"
LICENSE = "WTFPL"

#TODO: Use LICENSE once https://github.com/remcohaszing/pywakeonlan/issues/4 is fixed
LIC_FILES_CHKSUM = "file://setup.py;startline=18;endline=18;md5=3f056150ac7fad21b51033a5e4ad0031"

inherit pypi

SRC_URI[md5sum] = "738cf2e3c01de8ff393d0863f5172383"
SRC_URI[sha256sum] = "860f38e4fe06366cec71cead3d4071763e9ae1265d43227d866a2ab30932a1ac"
