SUMMARY = "RestrictedPython is a defined subset of the Python language which allows to provide a program input into a trusted environment"
HOMEPAGE = "http://pypi.python.org/pypi/RestrictedPython"
LICENSE = "ZPL-2.1"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=78ccb3640dc841e1baecb3e27a6966b2"

inherit pypi

PYPI_PACKAGE = "RestrictedPython"

SRC_URI[md5sum] = "f7a747a02fcb6eb72bd3227c0710abc3"
SRC_URI[sha256sum] = "9df16603db24c9d40de285da9e57d43d934f656cf90fd034fd58ff1f8a79c027"
