SUMMARY = "attrs is the Python package that will bring back the joy of writing classes by relieving you from the drudgery of implementing object protocols (aka dunder methods)."
HOMEPAGE = "https://www.attrs.org/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d4ab25949a73fe7d4fdee93bcbdbf8ff"

PYPI_PACKAGE = "attrs"

inherit pypi

SRC_URI[md5sum] = "2be7bce157988928f5ff2bb50a0b510d"
SRC_URI[sha256sum] = "f0b870f674851ecbfbbbd364d6b5cbdff9dcedbc7f3f5e18a6891057f21fe399"

