SUMMARY = "Convert Voluptuous schemas to dictionaries so they can be serialized."
HOMEPAGE = "http://github.com/balloob/voluptuous-serialize"
LICENSE = "Apache-2.0"
# FIXME: Github project has LICENSE file, but not the archive from
# https://pypi.org/project/voluptuous-serialize/
LIC_FILES_CHKSUM = "file://setup.py;md5=5175a738aa67dc6b0be1450080a9b36b"

inherit pypi

SRC_URI[md5sum] = "e74c60eea4c2ec011e285406f5bde308"
SRC_URI[sha256sum] = "d30fef4f1aba251414ec0b315df81a06da7bf35201dcfb1f6db5253d738a154f"

